/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param providerId 
 * @param titleType 
 * @param status 
 */
@Serializable

data class AddToWatchlist (

    @SerialName(value = "providerId")
    val providerId: kotlin.Long,

    @SerialName(value = "titleType")
    val titleType: AddToWatchlist.TitleType,

    @SerialName(value = "status")
    val status: AddToWatchlist.Status? = null

) {

    /**
     * 
     *
     * Values: MOVIE,TV_SERIES
     */
    @Serializable
    enum class TitleType(val value: kotlin.String) {
        @SerialName(value = "MOVIE") MOVIE("MOVIE"),
        @SerialName(value = "TV_SERIES") TV_SERIES("TV_SERIES");
    }
    /**
     * 
     *
     * Values: WATCHLIST,WATCHING,COMPLETED,ON_HOLD,DROPPED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "WATCHLIST") WATCHLIST("WATCHLIST"),
        @SerialName(value = "WATCHING") WATCHING("WATCHING"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "ON_HOLD") ON_HOLD("ON_HOLD"),
        @SerialName(value = "DROPPED") DROPPED("DROPPED");
    }

}

