/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fetchedAt 
 * @param offerType 
 * @param serviceId 
 * @param serviceName 
 * @param link 
 * @param logoUrl 
 */
@Serializable

data class AvailabilityResponse (

    @Contextual @SerialName(value = "fetchedAt")
    val fetchedAt: java.time.OffsetDateTime,

    @SerialName(value = "offerType")
    val offerType: AvailabilityResponse.OfferType,

    @SerialName(value = "serviceId")
    val serviceId: kotlin.Long,

    @SerialName(value = "serviceName")
    val serviceName: kotlin.String,

    @SerialName(value = "link")
    val link: kotlin.String? = null,

    @SerialName(value = "logoUrl")
    val logoUrl: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: FLATRATE,RENT,BUY,ADS,FREE
     */
    @Serializable
    enum class OfferType(val value: kotlin.String) {
        @SerialName(value = "FLATRATE") FLATRATE("FLATRATE"),
        @SerialName(value = "RENT") RENT("RENT"),
        @SerialName(value = "BUY") BUY("BUY"),
        @SerialName(value = "ADS") ADS("ADS"),
        @SerialName(value = "FREE") FREE("FREE");
    }

}

