/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param airedEpisodes 
 * @param alreadyWatched 
 * @param newlyMarked 
 * @param titleId 
 * @param watchedEpisodes 
 */
@Serializable

data class BulkMarkResponse (

    @SerialName(value = "airedEpisodes")
    val airedEpisodes: kotlin.Int,

    @SerialName(value = "alreadyWatched")
    val alreadyWatched: kotlin.Int,

    @SerialName(value = "newlyMarked")
    val newlyMarked: kotlin.Int,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long,

    @SerialName(value = "watchedEpisodes")
    val watchedEpisodes: kotlin.Int

) {


}

