/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param aired 
 * @param code 
 * @param episodeNumber 
 * @param id 
 * @param seasonNumber 
 * @param watchCount 
 * @param watched 
 * @param airDate 
 * @param name 
 * @param overview 
 * @param runtimeMinutes 
 * @param stillUrl 
 */
@Serializable

data class EpisodeResponse (

    @SerialName(value = "aired")
    val aired: kotlin.Boolean,

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "episodeNumber")
    val episodeNumber: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Int,

    @SerialName(value = "watchCount")
    val watchCount: kotlin.Int,

    @SerialName(value = "watched")
    val watched: kotlin.Boolean,

    @Contextual @SerialName(value = "airDate")
    val airDate: java.time.LocalDate? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "runtimeMinutes")
    val runtimeMinutes: kotlin.Int? = null,

    @SerialName(value = "stillUrl")
    val stillUrl: kotlin.String? = null

) {


}

