/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sourceRef 
 * @param titleId 
 * @param episodeId 
 * @param rating 
 * @param titleText 
 * @param watchedAt 
 */
@Serializable

data class ImportSelection (

    @SerialName(value = "sourceRef")
    val sourceRef: kotlin.String,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long,

    @SerialName(value = "episodeId")
    val episodeId: kotlin.Long? = null,

    @Contextual @SerialName(value = "rating")
    val rating: java.math.BigDecimal? = null,

    @SerialName(value = "titleText")
    val titleText: kotlin.String? = null,

    @Contextual @SerialName(value = "watchedAt")
    val watchedAt: java.time.LocalDate? = null

) {


}

