/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param failed 
 * @param imported 
 * @param problems 
 * @param skipped 
 */
@Serializable

data class ImportResultResponse (

    @SerialName(value = "failed")
    val failed: kotlin.Int,

    @SerialName(value = "imported")
    val imported: kotlin.Int,

    @SerialName(value = "problems")
    val problems: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "skipped")
    val skipped: kotlin.Int

) {


}

