/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.ImportCandidateResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param candidates 
 * @param sourceRef 
 * @param status 
 * @param titleText 
 * @param episodeCode 
 * @param episodeId 
 * @param episodeName 
 * @param episodeNumber 
 * @param imdbId 
 * @param note 
 * @param rating 
 * @param seasonNumber 
 * @param titleId 
 * @param titleName 
 * @param watchedAt 
 * @param year 
 */
@Serializable

data class ImportRowResponse (

    @SerialName(value = "candidates")
    val candidates: kotlin.collections.List<ImportCandidateResponse>,

    @SerialName(value = "sourceRef")
    val sourceRef: kotlin.String,

    @SerialName(value = "status")
    val status: ImportRowResponse.Status,

    @SerialName(value = "titleText")
    val titleText: kotlin.String,

    @SerialName(value = "episodeCode")
    val episodeCode: kotlin.String? = null,

    @SerialName(value = "episodeId")
    val episodeId: kotlin.Long? = null,

    @SerialName(value = "episodeName")
    val episodeName: kotlin.String? = null,

    @SerialName(value = "episodeNumber")
    val episodeNumber: kotlin.Int? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @Contextual @SerialName(value = "rating")
    val rating: java.math.BigDecimal? = null,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Int? = null,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long? = null,

    @SerialName(value = "titleName")
    val titleName: kotlin.String? = null,

    @Contextual @SerialName(value = "watchedAt")
    val watchedAt: java.time.LocalDate? = null,

    @SerialName(value = "year")
    val year: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: MATCHED,AMBIGUOUS,UNMATCHED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "MATCHED") MATCHED("MATCHED"),
        @SerialName(value = "AMBIGUOUS") AMBIGUOUS("AMBIGUOUS"),
        @SerialName(value = "UNMATCHED") UNMATCHED("UNMATCHED");
    }

}

