/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.ImportRowResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param alreadyImported 
 * @param problems 
 * @param rows 
 * @param source 
 * @param warnings 
 */
@Serializable

data class ImportPreviewResponse (

    @SerialName(value = "alreadyImported")
    val alreadyImported: kotlin.Int,

    @SerialName(value = "problems")
    val problems: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "rows")
    val rows: kotlin.collections.List<ImportRowResponse>,

    @SerialName(value = "source")
    val source: ImportPreviewResponse.Source,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {

    /**
     * 
     *
     * Values: WATCH_GURU,IMDB,LETTERBOXD,NETFLIX,UNKNOWN
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "WATCH_GURU") WATCH_GURU("WATCH_GURU"),
        @SerialName(value = "IMDB") IMDB("IMDB"),
        @SerialName(value = "LETTERBOXD") LETTERBOXD("LETTERBOXD"),
        @SerialName(value = "NETFLIX") NETFLIX("NETFLIX"),
        @SerialName(value = "UNKNOWN") UNKNOWN("UNKNOWN");
    }

}

