/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param itemId 
 * @param status 
 * @param notes 
 * @param rating 
 */
@Serializable

data class LibraryEntry (

    @SerialName(value = "itemId")
    val itemId: kotlin.Long,

    @SerialName(value = "status")
    val status: LibraryEntry.Status,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @Contextual @SerialName(value = "rating")
    val rating: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: WATCHLIST,WATCHING,COMPLETED,ON_HOLD,DROPPED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "WATCHLIST") WATCHLIST("WATCHLIST"),
        @SerialName(value = "WATCHING") WATCHING("WATCHING"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "ON_HOLD") ON_HOLD("ON_HOLD"),
        @SerialName(value = "DROPPED") DROPPED("DROPPED");
    }

}

