/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.StreamingServiceResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param service 
 * @param status 
 * @param syncEnabled 
 * @param accountLabel 
 * @param lastSyncAt 
 * @param lastSyncError 
 */
@Serializable

data class LinkedAccountResponse (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "service")
    val service: StreamingServiceResponse,

    @SerialName(value = "status")
    val status: LinkedAccountResponse.Status,

    @SerialName(value = "syncEnabled")
    val syncEnabled: kotlin.Boolean,

    @SerialName(value = "accountLabel")
    val accountLabel: kotlin.String? = null,

    @Contextual @SerialName(value = "lastSyncAt")
    val lastSyncAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "lastSyncError")
    val lastSyncError: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: PENDING,CONNECTED,ERROR,REVOKED,DISCONNECTED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "PENDING") PENDING("PENDING"),
        @SerialName(value = "CONNECTED") CONNECTED("CONNECTED"),
        @SerialName(value = "ERROR") ERROR("ERROR"),
        @SerialName(value = "REVOKED") REVOKED("REVOKED"),
        @SerialName(value = "DISCONNECTED") DISCONNECTED("DISCONNECTED");
    }

}

