/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param episodeId 
 * @param streamingServiceId 
 * @param watchedAt 
 */
@Serializable

data class LogEpisodeWatched (

    @SerialName(value = "episodeId")
    val episodeId: kotlin.Long,

    @SerialName(value = "streamingServiceId")
    val streamingServiceId: kotlin.Long? = null,

    @Contextual @SerialName(value = "watchedAt")
    val watchedAt: java.time.OffsetDateTime? = null

) {


}

