/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.LinkedAccountResponse
import dev.dhuelin.watchguru.api.models.SyncRunResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param connected 
 * @param recentRuns 
 * @param requiresAccountName 
 * @param service 
 * @param serviceName 
 * @param account 
 */
@Serializable

data class MediaServerStatusResponse (

    @SerialName(value = "connected")
    val connected: kotlin.Boolean,

    @SerialName(value = "recentRuns")
    val recentRuns: kotlin.collections.List<SyncRunResponse>,

    @SerialName(value = "requiresAccountName")
    val requiresAccountName: kotlin.Boolean,

    @SerialName(value = "service")
    val service: kotlin.String,

    @SerialName(value = "serviceName")
    val serviceName: kotlin.String,

    @SerialName(value = "account")
    val account: LinkedAccountResponse? = null

) {


}

