/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.LinkedAccountResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param account 
 * @param service 
 * @param serviceName 
 * @param setUpHint 
 * @param webhookUrl 
 */
@Serializable

data class MediaServerConnectionResponse (

    @SerialName(value = "account")
    val account: LinkedAccountResponse,

    @SerialName(value = "service")
    val service: kotlin.String,

    @SerialName(value = "serviceName")
    val serviceName: kotlin.String,

    @SerialName(value = "setUpHint")
    val setUpHint: kotlin.String,

    @SerialName(value = "webhookUrl")
    val webhookUrl: kotlin.String

) {


}

