/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.SeriesNotificationResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param registeredDevices 
 * @param series 
 */
@Serializable

data class NotificationSettingsResponse (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "registeredDevices")
    val registeredDevices: kotlin.Int,

    @SerialName(value = "series")
    val series: kotlin.collections.List<SeriesNotificationResponse>

) {


}

