/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param platform 
 * @param token 
 */
@Serializable

data class RegisterDevice (

    @SerialName(value = "platform")
    val platform: RegisterDevice.Platform,

    @SerialName(value = "token")
    val token: kotlin.String

) {

    /**
     * 
     *
     * Values: IOS,ANDROID
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "IOS") IOS("IOS"),
        @SerialName(value = "ANDROID") ANDROID("ANDROID");
    }

}

