/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.SearchHit

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param results 
 * @param totalPages 
 * @param totalResults 
 */
@Serializable

data class SearchResponse (

    @SerialName(value = "page")
    val page: kotlin.Int,

    @SerialName(value = "results")
    val results: kotlin.collections.List<SearchHit>,

    @SerialName(value = "totalPages")
    val totalPages: kotlin.Int,

    @SerialName(value = "totalResults")
    val totalResults: kotlin.Long

) {


}

