/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param providerId 
 * @param title 
 * @param titleType 
 * @param originalTitle 
 * @param overview 
 * @param posterUrl 
 * @param providerRating 
 * @param providerVoteCount 
 * @param releaseDate 
 */
@Serializable

data class SearchHit (

    @SerialName(value = "providerId")
    val providerId: kotlin.Long,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "titleType")
    val titleType: SearchHit.TitleType,

    @SerialName(value = "originalTitle")
    val originalTitle: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null,

    @Contextual @SerialName(value = "providerRating")
    val providerRating: java.math.BigDecimal? = null,

    @SerialName(value = "providerVoteCount")
    val providerVoteCount: kotlin.Int? = null,

    @Contextual @SerialName(value = "releaseDate")
    val releaseDate: java.time.LocalDate? = null

) {

    /**
     * 
     *
     * Values: MOVIE,TV_SERIES
     */
    @Serializable
    enum class TitleType(val value: kotlin.String) {
        @SerialName(value = "MOVIE") MOVIE("MOVIE"),
        @SerialName(value = "TV_SERIES") TV_SERIES("TV_SERIES");
    }

}

