/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.SeasonResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param primaryTitle 
 * @param seasons 
 * @param titleId 
 */
@Serializable

data class SeasonsResponse (

    @SerialName(value = "primaryTitle")
    val primaryTitle: kotlin.String,

    @SerialName(value = "seasons")
    val seasons: kotlin.collections.List<SeasonResponse>,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long

) {


}

