/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.EpisodeResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param airedEpisodes 
 * @param episodes 
 * @param id 
 * @param seasonNumber 
 * @param watchedEpisodes 
 * @param airDate 
 * @param name 
 * @param overview 
 * @param posterUrl 
 */
@Serializable

data class SeasonResponse (

    @SerialName(value = "airedEpisodes")
    val airedEpisodes: kotlin.Int,

    @SerialName(value = "episodes")
    val episodes: kotlin.collections.List<EpisodeResponse>,

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Int,

    @SerialName(value = "watchedEpisodes")
    val watchedEpisodes: kotlin.Int,

    @Contextual @SerialName(value = "airDate")
    val airDate: java.time.LocalDate? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null

) {


}

