/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param airedEpisodes 
 * @param percentComplete 
 * @param watchedEpisodes 
 */
@Serializable

data class SeriesProgress (

    @SerialName(value = "airedEpisodes")
    val airedEpisodes: kotlin.Int,

    @SerialName(value = "percentComplete")
    val percentComplete: kotlin.Int,

    @SerialName(value = "watchedEpisodes")
    val watchedEpisodes: kotlin.Int

) {


}

