/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param expiresIn 
 * @param refreshToken 
 * @param refreshTokenExpiresAt 
 * @param tokenType 
 */
@Serializable

data class SessionResponse (

    @SerialName(value = "accessToken")
    val accessToken: kotlin.String,

    @SerialName(value = "expiresIn")
    val expiresIn: kotlin.Long,

    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String,

    @Contextual @SerialName(value = "refreshTokenExpiresAt")
    val refreshTokenExpiresAt: java.time.OffsetDateTime,

    @SerialName(value = "tokenType")
    val tokenType: kotlin.String

) {


}

