/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param slug 
 * @param supportsSync 
 * @param logoUrl 
 */
@Serializable

data class StreamingServiceResponse (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "slug")
    val slug: kotlin.String,

    @SerialName(value = "supportsSync")
    val supportsSync: kotlin.Boolean,

    @SerialName(value = "logoUrl")
    val logoUrl: kotlin.String? = null

) {


}

