/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param itemsFailed 
 * @param itemsImported 
 * @param itemsSkipped 
 * @param startedAt 
 * @param status 
 * @param errorMessage 
 * @param finishedAt 
 */
@Serializable

data class SyncRunResponse (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "itemsFailed")
    val itemsFailed: kotlin.Int,

    @SerialName(value = "itemsImported")
    val itemsImported: kotlin.Int,

    @SerialName(value = "itemsSkipped")
    val itemsSkipped: kotlin.Int,

    @Contextual @SerialName(value = "startedAt")
    val startedAt: java.time.OffsetDateTime,

    @SerialName(value = "status")
    val status: SyncRunResponse.Status,

    @SerialName(value = "errorMessage")
    val errorMessage: kotlin.String? = null,

    @Contextual @SerialName(value = "finishedAt")
    val finishedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: RUNNING,SUCCESS,PARTIAL,FAILED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "RUNNING") RUNNING("RUNNING"),
        @SerialName(value = "SUCCESS") SUCCESS("SUCCESS"),
        @SerialName(value = "PARTIAL") PARTIAL("PARTIAL"),
        @SerialName(value = "FAILED") FAILED("FAILED");
    }

}

