/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.AvailabilityResponse
import dev.dhuelin.watchguru.api.models.GenreResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param availability 
 * @param genres 
 * @param id 
 * @param primaryTitle 
 * @param providerId 
 * @param titleType 
 * @param availabilityCheckedAt 
 * @param backdropUrl 
 * @param imdbId 
 * @param imdbRating 
 * @param imdbUrl 
 * @param lastAirDate 
 * @param numberOfEpisodes 
 * @param numberOfSeasons 
 * @param originalTitle 
 * @param overview 
 * @param posterUrl 
 * @param productionStatus 
 * @param providerRating 
 * @param providerVoteCount 
 * @param releaseDate 
 * @param runtimeMinutes 
 * @param tagline 
 */
@Serializable

data class TitleResponse (

    @SerialName(value = "availability")
    val availability: kotlin.collections.List<AvailabilityResponse>,

    @SerialName(value = "genres")
    val genres: kotlin.collections.List<GenreResponse>,

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "primaryTitle")
    val primaryTitle: kotlin.String,

    @SerialName(value = "providerId")
    val providerId: kotlin.Long,

    @SerialName(value = "titleType")
    val titleType: TitleResponse.TitleType,

    @Contextual @SerialName(value = "availabilityCheckedAt")
    val availabilityCheckedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "backdropUrl")
    val backdropUrl: kotlin.String? = null,

    @SerialName(value = "imdbId")
    val imdbId: kotlin.String? = null,

    @Contextual @SerialName(value = "imdbRating")
    val imdbRating: java.math.BigDecimal? = null,

    @SerialName(value = "imdbUrl")
    val imdbUrl: kotlin.String? = null,

    @Contextual @SerialName(value = "lastAirDate")
    val lastAirDate: java.time.LocalDate? = null,

    @SerialName(value = "numberOfEpisodes")
    val numberOfEpisodes: kotlin.Int? = null,

    @SerialName(value = "numberOfSeasons")
    val numberOfSeasons: kotlin.Int? = null,

    @SerialName(value = "originalTitle")
    val originalTitle: kotlin.String? = null,

    @SerialName(value = "overview")
    val overview: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null,

    @SerialName(value = "productionStatus")
    val productionStatus: kotlin.String? = null,

    @Contextual @SerialName(value = "providerRating")
    val providerRating: java.math.BigDecimal? = null,

    @SerialName(value = "providerVoteCount")
    val providerVoteCount: kotlin.Int? = null,

    @Contextual @SerialName(value = "releaseDate")
    val releaseDate: java.time.LocalDate? = null,

    @SerialName(value = "runtimeMinutes")
    val runtimeMinutes: kotlin.Int? = null,

    @SerialName(value = "tagline")
    val tagline: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: MOVIE,TV_SERIES
     */
    @Serializable
    enum class TitleType(val value: kotlin.String) {
        @SerialName(value = "MOVIE") MOVIE("MOVIE"),
        @SerialName(value = "TV_SERIES") TV_SERIES("TV_SERIES");
    }

}

