/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param airedEpisodes 
 * @param percentComplete 
 * @param primaryTitle 
 * @param remainingMinutes 
 * @param titleId 
 * @param watchedEpisodes 
 * @param nextEpisodeCode 
 * @param nextEpisodeId 
 * @param nextEpisodeName 
 */
@Serializable

data class TitleProgress (

    @SerialName(value = "airedEpisodes")
    val airedEpisodes: kotlin.Int,

    @SerialName(value = "percentComplete")
    val percentComplete: kotlin.Int,

    @SerialName(value = "primaryTitle")
    val primaryTitle: kotlin.String,

    @SerialName(value = "remainingMinutes")
    val remainingMinutes: kotlin.Int,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long,

    @SerialName(value = "watchedEpisodes")
    val watchedEpisodes: kotlin.Int,

    @SerialName(value = "nextEpisodeCode")
    val nextEpisodeCode: kotlin.String? = null,

    @SerialName(value = "nextEpisodeId")
    val nextEpisodeId: kotlin.Long? = null,

    @SerialName(value = "nextEpisodeName")
    val nextEpisodeName: kotlin.String? = null

) {


}

