/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param displayName 
 * @param language 
 * @param region 
 * @param timeZone 
 */
@Serializable

data class UpdateProfile (

    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,

    @SerialName(value = "language")
    val language: kotlin.String? = null,

    @SerialName(value = "region")
    val region: kotlin.String? = null,

    @SerialName(value = "timeZone")
    val timeZone: kotlin.String? = null

) {


}

