/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param airedEpisodes 
 * @param nextEpisodeCode 
 * @param nextEpisodeId 
 * @param primaryTitle 
 * @param titleId 
 * @param watchedEpisodes 
 * @param lastWatchedAt 
 * @param nextEpisodeName 
 * @param nextEpisodeStillUrl 
 * @param posterUrl 
 */
@Serializable

data class UpNextResponse (

    @SerialName(value = "airedEpisodes")
    val airedEpisodes: kotlin.Int,

    @SerialName(value = "nextEpisodeCode")
    val nextEpisodeCode: kotlin.String,

    @SerialName(value = "nextEpisodeId")
    val nextEpisodeId: kotlin.Long,

    @SerialName(value = "primaryTitle")
    val primaryTitle: kotlin.String,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long,

    @SerialName(value = "watchedEpisodes")
    val watchedEpisodes: kotlin.Int,

    @Contextual @SerialName(value = "lastWatchedAt")
    val lastWatchedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "nextEpisodeName")
    val nextEpisodeName: kotlin.String? = null,

    @SerialName(value = "nextEpisodeStillUrl")
    val nextEpisodeStillUrl: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null

) {


}

