/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param primaryTitle 
 * @param rewatch 
 * @param titleId 
 * @param watchedAt 
 * @param episodeCode 
 * @param episodeId 
 * @param episodeName 
 * @param minutesWatched 
 * @param streamingServiceName 
 */
@Serializable

data class WatchEventResponse (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "primaryTitle")
    val primaryTitle: kotlin.String,

    @SerialName(value = "rewatch")
    val rewatch: kotlin.Boolean,

    @SerialName(value = "titleId")
    val titleId: kotlin.Long,

    @Contextual @SerialName(value = "watchedAt")
    val watchedAt: java.time.OffsetDateTime,

    @SerialName(value = "episodeCode")
    val episodeCode: kotlin.String? = null,

    @SerialName(value = "episodeId")
    val episodeId: kotlin.Long? = null,

    @SerialName(value = "episodeName")
    val episodeName: kotlin.String? = null,

    @SerialName(value = "minutesWatched")
    val minutesWatched: kotlin.Int? = null,

    @SerialName(value = "streamingServiceName")
    val streamingServiceName: kotlin.String? = null

) {


}

