/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.Bucket
import dev.dhuelin.watchguru.api.models.MonthBucket

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param byGenre 
 * @param byMonth 
 * @param byService 
 * @param byStatus 
 * @param currentStreakDays 
 * @param distinctTitles 
 * @param longestStreakDays 
 * @param minutesLast30Days 
 * @param minutesLast365Days 
 * @param topTitles 
 * @param totalEpisodeViewings 
 * @param totalMinutes 
 * @param totalMovieViewings 
 * @param firstWatchedAt 
 * @param lastWatchedAt 
 */
@Serializable

data class WatchStats (

    @SerialName(value = "byGenre")
    val byGenre: kotlin.collections.List<Bucket>,

    @SerialName(value = "byMonth")
    val byMonth: kotlin.collections.List<MonthBucket>,

    @SerialName(value = "byService")
    val byService: kotlin.collections.List<Bucket>,

    @SerialName(value = "byStatus")
    val byStatus: kotlin.collections.Map<kotlin.String, kotlin.Long>,

    @SerialName(value = "currentStreakDays")
    val currentStreakDays: kotlin.Int,

    @SerialName(value = "distinctTitles")
    val distinctTitles: kotlin.Long,

    @SerialName(value = "longestStreakDays")
    val longestStreakDays: kotlin.Int,

    @SerialName(value = "minutesLast30Days")
    val minutesLast30Days: kotlin.Long,

    @SerialName(value = "minutesLast365Days")
    val minutesLast365Days: kotlin.Long,

    @SerialName(value = "topTitles")
    val topTitles: kotlin.collections.List<Bucket>,

    @SerialName(value = "totalEpisodeViewings")
    val totalEpisodeViewings: kotlin.Long,

    @SerialName(value = "totalMinutes")
    val totalMinutes: kotlin.Long,

    @SerialName(value = "totalMovieViewings")
    val totalMovieViewings: kotlin.Long,

    @Contextual @SerialName(value = "firstWatchedAt")
    val firstWatchedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "lastWatchedAt")
    val lastWatchedAt: java.time.OffsetDateTime? = null

) {


}

