/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.dhuelin.watchguru.api.models

import dev.dhuelin.watchguru.api.models.SeriesProgress
import dev.dhuelin.watchguru.api.models.TitleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param addedAt 
 * @param favorite 
 * @param id 
 * @param priority 
 * @param status 
 * @param title 
 * @param completedAt 
 * @param notes 
 * @param progress 
 * @param startedAt 
 * @param userRating 
 */
@Serializable

data class WatchlistItemResponse (

    @Contextual @SerialName(value = "addedAt")
    val addedAt: java.time.OffsetDateTime,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    @SerialName(value = "id")
    val id: kotlin.Long,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @SerialName(value = "status")
    val status: WatchlistItemResponse.Status,

    @SerialName(value = "title")
    val title: TitleResponse,

    @Contextual @SerialName(value = "completedAt")
    val completedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @SerialName(value = "progress")
    val progress: SeriesProgress? = null,

    @Contextual @SerialName(value = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "userRating")
    val userRating: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: WATCHLIST,WATCHING,COMPLETED,ON_HOLD,DROPPED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "WATCHLIST") WATCHLIST("WATCHLIST"),
        @SerialName(value = "WATCHING") WATCHING("WATCHING"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "ON_HOLD") ON_HOLD("ON_HOLD"),
        @SerialName(value = "DROPPED") DROPPED("DROPPED");
    }

}

