package dev.dhuelin.watchguru.data

/**
 * Where this install's push token comes from.
 *
 * An interface with one real caller, because the thing behind it is the one
 * part of notifications that cannot be built yet: a token comes from Firebase
 * Cloud Messaging, FCM needs a `google-services.json`, and that file is
 * generated by a Firebase project nobody has created (#37).
 *
 * Everything on this side of the seam is finished and testable -- registering,
 * the settings screen, the per-series switches, forgetting the device on
 * sign-out. Only the token is missing, and when the project exists this becomes
 * one implementation rather than a change to any of it.
 */
interface PushTokens {

    /**
     * This install's token, or null when there is none to be had.
     *
     * Null is an ordinary answer rather than an error. A device with no Play
     * Services, a user who has refused notifications, and a build with no
     * Firebase project are all the same thing to every caller: nothing to
     * register.
     */
    suspend fun current(): String?
}

/**
 * What ships today: no token, because there is no FCM project to issue one.
 *
 * Deliberately not a fake token. A plausible-looking string would be accepted
 * by the backend, counted as a registered device, and then silently fail to
 * deliver anything -- so the settings screen would claim notifications are
 * working when nothing could possibly arrive. Returning null makes the screen
 * say the true thing instead.
 *
 * Replacing this means adding the `com.google.gms.google-services` plugin, the
 * `firebase-messaging` dependency and the project's own `google-services.json`,
 * then calling `FirebaseMessaging.getInstance().token`. That is #37, and it
 * needs credentials rather than code.
 */
class UnavailablePushTokens : PushTokens {
    override suspend fun current(): String? = null
}
