//
// AddToWatchlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddToWatchlist: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case watchlist = "WATCHLIST"
        case watching = "WATCHING"
        case completed = "COMPLETED"
        case onHold = "ON_HOLD"
        case dropped = "DROPPED"
    }
    public enum TitleType: String, Sendable, Codable, CaseIterable {
        case movie = "MOVIE"
        case tvSeries = "TV_SERIES"
    }
    public static let providerIdRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var providerId: Int64
    public var status: Status?
    public var titleType: TitleType

    public init(providerId: Int64, status: Status? = nil, titleType: TitleType) {
        self.providerId = providerId
        self.status = status
        self.titleType = titleType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerId
        case status
        case titleType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(titleType, forKey: .titleType)
    }
}

