//
// AvailabilityResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AvailabilityResponse: Sendable, Codable, Hashable {

    public enum OfferType: String, Sendable, Codable, CaseIterable {
        case flatrate = "FLATRATE"
        case rent = "RENT"
        case buy = "BUY"
        case ads = "ADS"
        case free = "FREE"
    }
    public var fetchedAt: Date
    public var link: String?
    public var logoUrl: String?
    public var offerType: OfferType
    public var serviceId: Int64
    public var serviceName: String

    public init(fetchedAt: Date, link: String? = nil, logoUrl: String? = nil, offerType: OfferType, serviceId: Int64, serviceName: String) {
        self.fetchedAt = fetchedAt
        self.link = link
        self.logoUrl = logoUrl
        self.offerType = offerType
        self.serviceId = serviceId
        self.serviceName = serviceName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fetchedAt
        case link
        case logoUrl
        case offerType
        case serviceId
        case serviceName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fetchedAt, forKey: .fetchedAt)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encode(offerType, forKey: .offerType)
        try container.encode(serviceId, forKey: .serviceId)
        try container.encode(serviceName, forKey: .serviceName)
    }
}

