//
// Bucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Bucket: Sendable, Codable, Hashable {

    public var label: String
    public var minutes: Int64
    public var viewings: Int64

    public init(label: String, minutes: Int64, viewings: Int64) {
        self.label = label
        self.minutes = minutes
        self.viewings = viewings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case minutes
        case viewings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(label, forKey: .label)
        try container.encode(minutes, forKey: .minutes)
        try container.encode(viewings, forKey: .viewings)
    }
}

