//
// BulkMarkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkMarkResponse: Sendable, Codable, Hashable {

    public var airedEpisodes: Int
    public var alreadyWatched: Int
    public var newlyMarked: Int
    public var titleId: Int64
    public var watchedEpisodes: Int

    public init(airedEpisodes: Int, alreadyWatched: Int, newlyMarked: Int, titleId: Int64, watchedEpisodes: Int) {
        self.airedEpisodes = airedEpisodes
        self.alreadyWatched = alreadyWatched
        self.newlyMarked = newlyMarked
        self.titleId = titleId
        self.watchedEpisodes = watchedEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airedEpisodes
        case alreadyWatched
        case newlyMarked
        case titleId
        case watchedEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(airedEpisodes, forKey: .airedEpisodes)
        try container.encode(alreadyWatched, forKey: .alreadyWatched)
        try container.encode(newlyMarked, forKey: .newlyMarked)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(watchedEpisodes, forKey: .watchedEpisodes)
    }
}

