//
// CommitImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommitImport: Sendable, Codable, Hashable {

    public static let rowsRule = ArrayRule(minItems: 0, maxItems: 10000, uniqueItems: false)
    public var rows: [ImportSelection]

    public init(rows: [ImportSelection]) {
        self.rows = rows
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rows
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rows, forKey: .rows)
    }
}

