//
// ConnectPlex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectPlex: Sendable, Codable, Hashable {

    public static let plexUsernameRule = StringRule(minLength: 0, maxLength: 128, pattern: nil)
    public var plexUsername: String?

    public init(plexUsername: String? = nil) {
        self.plexUsername = plexUsername
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plexUsername
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(plexUsername, forKey: .plexUsername)
    }
}

