//
// ConnectMediaServer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConnectMediaServer: Sendable, Codable, Hashable {

    public static let accountNameRule = StringRule(minLength: 0, maxLength: 128, pattern: nil)
    public var accountName: String?

    public init(accountName: String? = nil) {
        self.accountName = accountName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountName, forKey: .accountName)
    }
}

