//
// EpisodeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EpisodeResponse: Sendable, Codable, Hashable {

    public var airDate: Date?
    public var aired: Bool
    public var code: String
    public var episodeNumber: Int
    public var id: Int64
    public var name: String?
    public var overview: String?
    public var runtimeMinutes: Int?
    public var seasonNumber: Int
    public var stillUrl: String?
    public var watchCount: Int
    public var watched: Bool

    public init(airDate: Date? = nil, aired: Bool, code: String, episodeNumber: Int, id: Int64, name: String? = nil, overview: String? = nil, runtimeMinutes: Int? = nil, seasonNumber: Int, stillUrl: String? = nil, watchCount: Int, watched: Bool) {
        self.airDate = airDate
        self.aired = aired
        self.code = code
        self.episodeNumber = episodeNumber
        self.id = id
        self.name = name
        self.overview = overview
        self.runtimeMinutes = runtimeMinutes
        self.seasonNumber = seasonNumber
        self.stillUrl = stillUrl
        self.watchCount = watchCount
        self.watched = watched
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airDate
        case aired
        case code
        case episodeNumber
        case id
        case name
        case overview
        case runtimeMinutes
        case seasonNumber
        case stillUrl
        case watchCount
        case watched
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(airDate, forKey: .airDate)
        try container.encode(aired, forKey: .aired)
        try container.encode(code, forKey: .code)
        try container.encode(episodeNumber, forKey: .episodeNumber)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(overview, forKey: .overview)
        try container.encodeIfPresent(runtimeMinutes, forKey: .runtimeMinutes)
        try container.encode(seasonNumber, forKey: .seasonNumber)
        try container.encodeIfPresent(stillUrl, forKey: .stillUrl)
        try container.encode(watchCount, forKey: .watchCount)
        try container.encode(watched, forKey: .watched)
    }
}


extension EpisodeResponse: Identifiable {}
