//
// ExchangeToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ExchangeToken: Sendable, Codable, Hashable {

    public static let providerTokenRule = StringRule(minLength: 0, maxLength: 4096, pattern: nil)
    public var providerToken: String

    public init(providerToken: String) {
        self.providerToken = providerToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providerToken, forKey: .providerToken)
    }
}

