//
// ImportCandidateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportCandidateResponse: Sendable, Codable, Hashable {

    public var titleId: Int64
    public var titleName: String
    public var year: Int?

    public init(titleId: Int64, titleName: String, year: Int? = nil) {
        self.titleId = titleId
        self.titleName = titleName
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case titleId
        case titleName
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(titleName, forKey: .titleName)
        try container.encodeIfPresent(year, forKey: .year)
    }
}

