//
// ImportSelection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportSelection: Sendable, Codable, Hashable {

    public static let sourceRefRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let titleTextRule = StringRule(minLength: 0, maxLength: 512, pattern: nil)
    public var episodeId: Int64?
    public var sourceRef: String
    public var titleId: Int64
    public var titleText: String?
    public var watchedAt: Date?

    public init(episodeId: Int64? = nil, sourceRef: String, titleId: Int64, titleText: String? = nil, watchedAt: Date? = nil) {
        self.episodeId = episodeId
        self.sourceRef = sourceRef
        self.titleId = titleId
        self.titleText = titleText
        self.watchedAt = watchedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episodeId
        case sourceRef
        case titleId
        case titleText
        case watchedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(episodeId, forKey: .episodeId)
        try container.encode(sourceRef, forKey: .sourceRef)
        try container.encode(titleId, forKey: .titleId)
        try container.encodeIfPresent(titleText, forKey: .titleText)
        try container.encodeIfPresent(watchedAt, forKey: .watchedAt)
    }
}

