//
// ImportPreviewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportPreviewResponse: Sendable, Codable, Hashable {

    public enum Source: String, Sendable, Codable, CaseIterable {
        case watchGuru = "WATCH_GURU"
        case imdb = "IMDB"
        case letterboxd = "LETTERBOXD"
        case netflix = "NETFLIX"
        case unknown = "UNKNOWN"
    }
    public var alreadyImported: Int
    public var problems: [String]
    public var rows: [ImportRowResponse]
    public var source: Source
    public var warnings: [String]

    public init(alreadyImported: Int, problems: [String], rows: [ImportRowResponse], source: Source, warnings: [String]) {
        self.alreadyImported = alreadyImported
        self.problems = problems
        self.rows = rows
        self.source = source
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alreadyImported
        case problems
        case rows
        case source
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(alreadyImported, forKey: .alreadyImported)
        try container.encode(problems, forKey: .problems)
        try container.encode(rows, forKey: .rows)
        try container.encode(source, forKey: .source)
        try container.encode(warnings, forKey: .warnings)
    }
}

