//
// ImportRowResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportRowResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case matched = "MATCHED"
        case ambiguous = "AMBIGUOUS"
        case unmatched = "UNMATCHED"
    }
    public var candidates: [ImportCandidateResponse]
    public var episodeCode: String?
    public var episodeId: Int64?
    public var episodeName: String?
    public var episodeNumber: Int?
    public var imdbId: String?
    public var note: String?
    public var rating: Double?
    public var seasonNumber: Int?
    public var sourceRef: String
    public var status: Status
    public var titleId: Int64?
    public var titleName: String?
    public var titleText: String
    public var watchedAt: Date?
    public var year: Int?

    public init(candidates: [ImportCandidateResponse], episodeCode: String? = nil, episodeId: Int64? = nil, episodeName: String? = nil, episodeNumber: Int? = nil, imdbId: String? = nil, note: String? = nil, rating: Double? = nil, seasonNumber: Int? = nil, sourceRef: String, status: Status, titleId: Int64? = nil, titleName: String? = nil, titleText: String, watchedAt: Date? = nil, year: Int? = nil) {
        self.candidates = candidates
        self.episodeCode = episodeCode
        self.episodeId = episodeId
        self.episodeName = episodeName
        self.episodeNumber = episodeNumber
        self.imdbId = imdbId
        self.note = note
        self.rating = rating
        self.seasonNumber = seasonNumber
        self.sourceRef = sourceRef
        self.status = status
        self.titleId = titleId
        self.titleName = titleName
        self.titleText = titleText
        self.watchedAt = watchedAt
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case candidates
        case episodeCode
        case episodeId
        case episodeName
        case episodeNumber
        case imdbId
        case note
        case rating
        case seasonNumber
        case sourceRef
        case status
        case titleId
        case titleName
        case titleText
        case watchedAt
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(candidates, forKey: .candidates)
        try container.encodeIfPresent(episodeCode, forKey: .episodeCode)
        try container.encodeIfPresent(episodeId, forKey: .episodeId)
        try container.encodeIfPresent(episodeName, forKey: .episodeName)
        try container.encodeIfPresent(episodeNumber, forKey: .episodeNumber)
        try container.encodeIfPresent(imdbId, forKey: .imdbId)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(seasonNumber, forKey: .seasonNumber)
        try container.encode(sourceRef, forKey: .sourceRef)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(titleId, forKey: .titleId)
        try container.encodeIfPresent(titleName, forKey: .titleName)
        try container.encode(titleText, forKey: .titleText)
        try container.encodeIfPresent(watchedAt, forKey: .watchedAt)
        try container.encodeIfPresent(year, forKey: .year)
    }
}

