//
// LibraryEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LibraryEntry: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case watchlist = "WATCHLIST"
        case watching = "WATCHING"
        case completed = "COMPLETED"
        case onHold = "ON_HOLD"
        case dropped = "DROPPED"
    }
    public var itemId: Int64
    public var notes: String?
    public var rating: Double?
    public var status: Status

    public init(itemId: Int64, notes: String? = nil, rating: Double? = nil, status: Status) {
        self.itemId = itemId
        self.notes = notes
        self.rating = rating
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId
        case notes
        case rating
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemId, forKey: .itemId)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encode(status, forKey: .status)
    }
}

