//
// LinkedAccountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LinkedAccountResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pending = "PENDING"
        case connected = "CONNECTED"
        case error = "ERROR"
        case revoked = "REVOKED"
        case disconnected = "DISCONNECTED"
    }
    public var accountLabel: String?
    public var id: Int64
    public var lastSyncAt: Date?
    public var lastSyncError: String?
    public var service: StreamingServiceResponse
    public var status: Status
    public var syncEnabled: Bool

    public init(accountLabel: String? = nil, id: Int64, lastSyncAt: Date? = nil, lastSyncError: String? = nil, service: StreamingServiceResponse, status: Status, syncEnabled: Bool) {
        self.accountLabel = accountLabel
        self.id = id
        self.lastSyncAt = lastSyncAt
        self.lastSyncError = lastSyncError
        self.service = service
        self.status = status
        self.syncEnabled = syncEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountLabel
        case id
        case lastSyncAt
        case lastSyncError
        case service
        case status
        case syncEnabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountLabel, forKey: .accountLabel)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(lastSyncAt, forKey: .lastSyncAt)
        try container.encodeIfPresent(lastSyncError, forKey: .lastSyncError)
        try container.encode(service, forKey: .service)
        try container.encode(status, forKey: .status)
        try container.encode(syncEnabled, forKey: .syncEnabled)
    }
}


extension LinkedAccountResponse: Identifiable {}
