//
// MarkWatchedUpTo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MarkWatchedUpTo: Sendable, Codable, Hashable {

    public var episodeId: Int64
    public var watchedAt: Date?

    public init(episodeId: Int64, watchedAt: Date? = nil) {
        self.episodeId = episodeId
        self.watchedAt = watchedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episodeId
        case watchedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(episodeId, forKey: .episodeId)
        try container.encodeIfPresent(watchedAt, forKey: .watchedAt)
    }
}

