//
// MediaServerConnectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MediaServerConnectionResponse: Sendable, Codable, Hashable {

    public var account: LinkedAccountResponse
    public var service: String
    public var serviceName: String
    public var setUpHint: String
    public var webhookUrl: String

    public init(account: LinkedAccountResponse, service: String, serviceName: String, setUpHint: String, webhookUrl: String) {
        self.account = account
        self.service = service
        self.serviceName = serviceName
        self.setUpHint = setUpHint
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case service
        case serviceName
        case setUpHint
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(service, forKey: .service)
        try container.encode(serviceName, forKey: .serviceName)
        try container.encode(setUpHint, forKey: .setUpHint)
        try container.encode(webhookUrl, forKey: .webhookUrl)
    }
}

