//
// MediaServerStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MediaServerStatusResponse: Sendable, Codable, Hashable {

    public var account: LinkedAccountResponse?
    public var connected: Bool
    public var recentRuns: [SyncRunResponse]
    public var requiresAccountName: Bool
    public var service: String
    public var serviceName: String

    public init(account: LinkedAccountResponse? = nil, connected: Bool, recentRuns: [SyncRunResponse], requiresAccountName: Bool, service: String, serviceName: String) {
        self.account = account
        self.connected = connected
        self.recentRuns = recentRuns
        self.requiresAccountName = requiresAccountName
        self.service = service
        self.serviceName = serviceName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case connected
        case recentRuns
        case requiresAccountName
        case service
        case serviceName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encode(connected, forKey: .connected)
        try container.encode(recentRuns, forKey: .recentRuns)
        try container.encode(requiresAccountName, forKey: .requiresAccountName)
        try container.encode(service, forKey: .service)
        try container.encode(serviceName, forKey: .serviceName)
    }
}

