//
// MonthBucket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MonthBucket: Sendable, Codable, Hashable {

    public var minutes: Int64
    public var month: Int
    public var viewings: Int64
    public var year: Int

    public init(minutes: Int64, month: Int, viewings: Int64, year: Int) {
        self.minutes = minutes
        self.month = month
        self.viewings = viewings
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case minutes
        case month
        case viewings
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(minutes, forKey: .minutes)
        try container.encode(month, forKey: .month)
        try container.encode(viewings, forKey: .viewings)
        try container.encode(year, forKey: .year)
    }
}

