//
// NotificationSettingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NotificationSettingsResponse: Sendable, Codable, Hashable {

    public var enabled: Bool
    public var registeredDevices: Int
    public var series: [SeriesNotificationResponse]

    public init(enabled: Bool, registeredDevices: Int, series: [SeriesNotificationResponse]) {
        self.enabled = enabled
        self.registeredDevices = registeredDevices
        self.series = series
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case registeredDevices
        case series
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(registeredDevices, forKey: .registeredDevices)
        try container.encode(series, forKey: .series)
    }
}

