//
// PlexStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlexStatusResponse: Sendable, Codable, Hashable {

    public var account: LinkedAccountResponse?
    public var connected: Bool
    public var recentRuns: [SyncRunResponse]

    public init(account: LinkedAccountResponse? = nil, connected: Bool, recentRuns: [SyncRunResponse]) {
        self.account = account
        self.connected = connected
        self.recentRuns = recentRuns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case connected
        case recentRuns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encode(connected, forKey: .connected)
        try container.encode(recentRuns, forKey: .recentRuns)
    }
}

