//
// PlexConnectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlexConnectionResponse: Sendable, Codable, Hashable {

    public var account: LinkedAccountResponse
    public var setUpHint: String
    public var webhookUrl: String

    public init(account: LinkedAccountResponse, setUpHint: String, webhookUrl: String) {
        self.account = account
        self.setUpHint = setUpHint
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case setUpHint
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(setUpHint, forKey: .setUpHint)
        try container.encode(webhookUrl, forKey: .webhookUrl)
    }
}

