//
// PreviewImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PreviewImport: Sendable, Codable, Hashable {

    public static let contentRule = StringRule(minLength: 0, maxLength: 5000000, pattern: nil)
    public var content: String

    public init(content: String) {
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
    }
}

