//
// RegisterDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterDevice: Sendable, Codable, Hashable {

    public enum Platform: String, Sendable, Codable, CaseIterable {
        case ios = "IOS"
        case android = "ANDROID"
    }
    public static let tokenRule = StringRule(minLength: 0, maxLength: 512, pattern: nil)
    public var platform: Platform
    public var token: String

    public init(platform: Platform, token: String) {
        self.platform = platform
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(token, forKey: .token)
    }
}

