//
// SearchHit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchHit: Sendable, Codable, Hashable {

    public enum TitleType: String, Sendable, Codable, CaseIterable {
        case movie = "MOVIE"
        case tvSeries = "TV_SERIES"
    }
    public var originalTitle: String?
    public var overview: String?
    public var posterUrl: String?
    public var providerId: Int64
    public var providerRating: Double?
    public var providerVoteCount: Int?
    public var releaseDate: Date?
    public var title: String
    public var titleType: TitleType

    public init(originalTitle: String? = nil, overview: String? = nil, posterUrl: String? = nil, providerId: Int64, providerRating: Double? = nil, providerVoteCount: Int? = nil, releaseDate: Date? = nil, title: String, titleType: TitleType) {
        self.originalTitle = originalTitle
        self.overview = overview
        self.posterUrl = posterUrl
        self.providerId = providerId
        self.providerRating = providerRating
        self.providerVoteCount = providerVoteCount
        self.releaseDate = releaseDate
        self.title = title
        self.titleType = titleType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case originalTitle
        case overview
        case posterUrl
        case providerId
        case providerRating
        case providerVoteCount
        case releaseDate
        case title
        case titleType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(originalTitle, forKey: .originalTitle)
        try container.encodeIfPresent(overview, forKey: .overview)
        try container.encodeIfPresent(posterUrl, forKey: .posterUrl)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(providerRating, forKey: .providerRating)
        try container.encodeIfPresent(providerVoteCount, forKey: .providerVoteCount)
        try container.encodeIfPresent(releaseDate, forKey: .releaseDate)
        try container.encode(title, forKey: .title)
        try container.encode(titleType, forKey: .titleType)
    }
}

