//
// SearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchResponse: Sendable, Codable, Hashable {

    public var page: Int
    public var results: [SearchHit]
    public var totalPages: Int
    public var totalResults: Int64

    public init(page: Int, results: [SearchHit], totalPages: Int, totalResults: Int64) {
        self.page = page
        self.results = results
        self.totalPages = totalPages
        self.totalResults = totalResults
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case results
        case totalPages
        case totalResults
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(results, forKey: .results)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(totalResults, forKey: .totalResults)
    }
}

