//
// SeasonsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SeasonsResponse: Sendable, Codable, Hashable {

    public var primaryTitle: String
    public var seasons: [SeasonResponse]
    public var titleId: Int64

    public init(primaryTitle: String, seasons: [SeasonResponse], titleId: Int64) {
        self.primaryTitle = primaryTitle
        self.seasons = seasons
        self.titleId = titleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case primaryTitle
        case seasons
        case titleId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(primaryTitle, forKey: .primaryTitle)
        try container.encode(seasons, forKey: .seasons)
        try container.encode(titleId, forKey: .titleId)
    }
}

