//
// SeasonResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SeasonResponse: Sendable, Codable, Hashable {

    public var airDate: Date?
    public var airedEpisodes: Int
    public var episodes: [EpisodeResponse]
    public var id: Int64
    public var name: String?
    public var overview: String?
    public var posterUrl: String?
    public var seasonNumber: Int
    public var watchedEpisodes: Int

    public init(airDate: Date? = nil, airedEpisodes: Int, episodes: [EpisodeResponse], id: Int64, name: String? = nil, overview: String? = nil, posterUrl: String? = nil, seasonNumber: Int, watchedEpisodes: Int) {
        self.airDate = airDate
        self.airedEpisodes = airedEpisodes
        self.episodes = episodes
        self.id = id
        self.name = name
        self.overview = overview
        self.posterUrl = posterUrl
        self.seasonNumber = seasonNumber
        self.watchedEpisodes = watchedEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airDate
        case airedEpisodes
        case episodes
        case id
        case name
        case overview
        case posterUrl
        case seasonNumber
        case watchedEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(airDate, forKey: .airDate)
        try container.encode(airedEpisodes, forKey: .airedEpisodes)
        try container.encode(episodes, forKey: .episodes)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(overview, forKey: .overview)
        try container.encodeIfPresent(posterUrl, forKey: .posterUrl)
        try container.encode(seasonNumber, forKey: .seasonNumber)
        try container.encode(watchedEpisodes, forKey: .watchedEpisodes)
    }
}


extension SeasonResponse: Identifiable {}
