//
// SeriesNotificationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SeriesNotificationResponse: Sendable, Codable, Hashable {

    public var newEpisodes: Bool
    public var titleId: Int64
    public var titleName: String

    public init(newEpisodes: Bool, titleId: Int64, titleName: String) {
        self.newEpisodes = newEpisodes
        self.titleId = titleId
        self.titleName = titleName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newEpisodes
        case titleId
        case titleName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newEpisodes, forKey: .newEpisodes)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(titleName, forKey: .titleName)
    }
}

