//
// SeriesProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SeriesProgress: Sendable, Codable, Hashable {

    public var airedEpisodes: Int
    public var percentComplete: Int
    public var watchedEpisodes: Int

    public init(airedEpisodes: Int, percentComplete: Int, watchedEpisodes: Int) {
        self.airedEpisodes = airedEpisodes
        self.percentComplete = percentComplete
        self.watchedEpisodes = watchedEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airedEpisodes
        case percentComplete
        case watchedEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(airedEpisodes, forKey: .airedEpisodes)
        try container.encode(percentComplete, forKey: .percentComplete)
        try container.encode(watchedEpisodes, forKey: .watchedEpisodes)
    }
}

