//
// SessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SessionResponse: Sendable, Codable, Hashable {

    public var accessToken: String
    public var expiresIn: Int64
    public var refreshToken: String
    public var refreshTokenExpiresAt: Date
    public var tokenType: String

    public init(accessToken: String, expiresIn: Int64, refreshToken: String, refreshTokenExpiresAt: Date, tokenType: String) {
        self.accessToken = accessToken
        self.expiresIn = expiresIn
        self.refreshToken = refreshToken
        self.refreshTokenExpiresAt = refreshTokenExpiresAt
        self.tokenType = tokenType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken
        case expiresIn
        case refreshToken
        case refreshTokenExpiresAt
        case tokenType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(refreshToken, forKey: .refreshToken)
        try container.encode(refreshTokenExpiresAt, forKey: .refreshTokenExpiresAt)
        try container.encode(tokenType, forKey: .tokenType)
    }
}

