//
// StreamingServiceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StreamingServiceResponse: Sendable, Codable, Hashable {

    public var id: Int64
    public var logoUrl: String?
    public var name: String
    public var slug: String
    public var supportsSync: Bool

    public init(id: Int64, logoUrl: String? = nil, name: String, slug: String, supportsSync: Bool) {
        self.id = id
        self.logoUrl = logoUrl
        self.name = name
        self.slug = slug
        self.supportsSync = supportsSync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case logoUrl
        case name
        case slug
        case supportsSync
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(supportsSync, forKey: .supportsSync)
    }
}


extension StreamingServiceResponse: Identifiable {}
