//
// SyncResultResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncResultResponse: Sendable, Codable, Hashable {

    public var failed: Int
    public var imported: Int
    public var problems: [String]
    public var skipped: Int

    public init(failed: Int, imported: Int, problems: [String], skipped: Int) {
        self.failed = failed
        self.imported = imported
        self.problems = problems
        self.skipped = skipped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case failed
        case imported
        case problems
        case skipped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(failed, forKey: .failed)
        try container.encode(imported, forKey: .imported)
        try container.encode(problems, forKey: .problems)
        try container.encode(skipped, forKey: .skipped)
    }
}

