//
// SyncRunResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SyncRunResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case running = "RUNNING"
        case success = "SUCCESS"
        case partial = "PARTIAL"
        case failed = "FAILED"
    }
    public var errorMessage: String?
    public var finishedAt: Date?
    public var id: Int64
    public var itemsFailed: Int
    public var itemsImported: Int
    public var itemsSkipped: Int
    public var startedAt: Date
    public var status: Status

    public init(errorMessage: String? = nil, finishedAt: Date? = nil, id: Int64, itemsFailed: Int, itemsImported: Int, itemsSkipped: Int, startedAt: Date, status: Status) {
        self.errorMessage = errorMessage
        self.finishedAt = finishedAt
        self.id = id
        self.itemsFailed = itemsFailed
        self.itemsImported = itemsImported
        self.itemsSkipped = itemsSkipped
        self.startedAt = startedAt
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errorMessage
        case finishedAt
        case id
        case itemsFailed
        case itemsImported
        case itemsSkipped
        case startedAt
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encodeIfPresent(finishedAt, forKey: .finishedAt)
        try container.encode(id, forKey: .id)
        try container.encode(itemsFailed, forKey: .itemsFailed)
        try container.encode(itemsImported, forKey: .itemsImported)
        try container.encode(itemsSkipped, forKey: .itemsSkipped)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
    }
}


extension SyncRunResponse: Identifiable {}
