//
// TitleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TitleResponse: Sendable, Codable, Hashable {

    public enum TitleType: String, Sendable, Codable, CaseIterable {
        case movie = "MOVIE"
        case tvSeries = "TV_SERIES"
    }
    public var availability: [AvailabilityResponse]
    public var backdropUrl: String?
    public var genres: [GenreResponse]
    public var id: Int64
    public var imdbId: String?
    public var imdbRating: Double?
    public var imdbUrl: String?
    public var lastAirDate: Date?
    public var numberOfEpisodes: Int?
    public var numberOfSeasons: Int?
    public var originalTitle: String?
    public var overview: String?
    public var posterUrl: String?
    public var primaryTitle: String
    public var productionStatus: String?
    public var providerId: Int64
    public var providerRating: Double?
    public var providerVoteCount: Int?
    public var releaseDate: Date?
    public var runtimeMinutes: Int?
    public var tagline: String?
    public var titleType: TitleType

    public init(availability: [AvailabilityResponse], backdropUrl: String? = nil, genres: [GenreResponse], id: Int64, imdbId: String? = nil, imdbRating: Double? = nil, imdbUrl: String? = nil, lastAirDate: Date? = nil, numberOfEpisodes: Int? = nil, numberOfSeasons: Int? = nil, originalTitle: String? = nil, overview: String? = nil, posterUrl: String? = nil, primaryTitle: String, productionStatus: String? = nil, providerId: Int64, providerRating: Double? = nil, providerVoteCount: Int? = nil, releaseDate: Date? = nil, runtimeMinutes: Int? = nil, tagline: String? = nil, titleType: TitleType) {
        self.availability = availability
        self.backdropUrl = backdropUrl
        self.genres = genres
        self.id = id
        self.imdbId = imdbId
        self.imdbRating = imdbRating
        self.imdbUrl = imdbUrl
        self.lastAirDate = lastAirDate
        self.numberOfEpisodes = numberOfEpisodes
        self.numberOfSeasons = numberOfSeasons
        self.originalTitle = originalTitle
        self.overview = overview
        self.posterUrl = posterUrl
        self.primaryTitle = primaryTitle
        self.productionStatus = productionStatus
        self.providerId = providerId
        self.providerRating = providerRating
        self.providerVoteCount = providerVoteCount
        self.releaseDate = releaseDate
        self.runtimeMinutes = runtimeMinutes
        self.tagline = tagline
        self.titleType = titleType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case availability
        case backdropUrl
        case genres
        case id
        case imdbId
        case imdbRating
        case imdbUrl
        case lastAirDate
        case numberOfEpisodes
        case numberOfSeasons
        case originalTitle
        case overview
        case posterUrl
        case primaryTitle
        case productionStatus
        case providerId
        case providerRating
        case providerVoteCount
        case releaseDate
        case runtimeMinutes
        case tagline
        case titleType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(availability, forKey: .availability)
        try container.encodeIfPresent(backdropUrl, forKey: .backdropUrl)
        try container.encode(genres, forKey: .genres)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(imdbId, forKey: .imdbId)
        try container.encodeIfPresent(imdbRating, forKey: .imdbRating)
        try container.encodeIfPresent(imdbUrl, forKey: .imdbUrl)
        try container.encodeIfPresent(lastAirDate, forKey: .lastAirDate)
        try container.encodeIfPresent(numberOfEpisodes, forKey: .numberOfEpisodes)
        try container.encodeIfPresent(numberOfSeasons, forKey: .numberOfSeasons)
        try container.encodeIfPresent(originalTitle, forKey: .originalTitle)
        try container.encodeIfPresent(overview, forKey: .overview)
        try container.encodeIfPresent(posterUrl, forKey: .posterUrl)
        try container.encode(primaryTitle, forKey: .primaryTitle)
        try container.encodeIfPresent(productionStatus, forKey: .productionStatus)
        try container.encode(providerId, forKey: .providerId)
        try container.encodeIfPresent(providerRating, forKey: .providerRating)
        try container.encodeIfPresent(providerVoteCount, forKey: .providerVoteCount)
        try container.encodeIfPresent(releaseDate, forKey: .releaseDate)
        try container.encodeIfPresent(runtimeMinutes, forKey: .runtimeMinutes)
        try container.encodeIfPresent(tagline, forKey: .tagline)
        try container.encode(titleType, forKey: .titleType)
    }
}


extension TitleResponse: Identifiable {}
