//
// TitleProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TitleProgress: Sendable, Codable, Hashable {

    public var airedEpisodes: Int
    public var nextEpisodeCode: String?
    public var nextEpisodeId: Int64?
    public var nextEpisodeName: String?
    public var percentComplete: Int
    public var primaryTitle: String
    public var remainingMinutes: Int
    public var titleId: Int64
    public var watchedEpisodes: Int

    public init(airedEpisodes: Int, nextEpisodeCode: String? = nil, nextEpisodeId: Int64? = nil, nextEpisodeName: String? = nil, percentComplete: Int, primaryTitle: String, remainingMinutes: Int, titleId: Int64, watchedEpisodes: Int) {
        self.airedEpisodes = airedEpisodes
        self.nextEpisodeCode = nextEpisodeCode
        self.nextEpisodeId = nextEpisodeId
        self.nextEpisodeName = nextEpisodeName
        self.percentComplete = percentComplete
        self.primaryTitle = primaryTitle
        self.remainingMinutes = remainingMinutes
        self.titleId = titleId
        self.watchedEpisodes = watchedEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airedEpisodes
        case nextEpisodeCode
        case nextEpisodeId
        case nextEpisodeName
        case percentComplete
        case primaryTitle
        case remainingMinutes
        case titleId
        case watchedEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(airedEpisodes, forKey: .airedEpisodes)
        try container.encodeIfPresent(nextEpisodeCode, forKey: .nextEpisodeCode)
        try container.encodeIfPresent(nextEpisodeId, forKey: .nextEpisodeId)
        try container.encodeIfPresent(nextEpisodeName, forKey: .nextEpisodeName)
        try container.encode(percentComplete, forKey: .percentComplete)
        try container.encode(primaryTitle, forKey: .primaryTitle)
        try container.encode(remainingMinutes, forKey: .remainingMinutes)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(watchedEpisodes, forKey: .watchedEpisodes)
    }
}

