//
// TraktAuthorizationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TraktAuthorizationResponse: Sendable, Codable, Hashable {

    public var authorizeUrl: String
    public var instructions: String

    public init(authorizeUrl: String, instructions: String) {
        self.authorizeUrl = authorizeUrl
        self.instructions = instructions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authorizeUrl
        case instructions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(authorizeUrl, forKey: .authorizeUrl)
        try container.encode(instructions, forKey: .instructions)
    }
}

