//
// UpdateProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateProfile: Sendable, Codable, Hashable {

    public static let displayNameRule = StringRule(minLength: 0, maxLength: 128, pattern: nil)
    public static let languageRule = StringRule(minLength: 0, maxLength: 16, pattern: nil)
    public static let regionRule = StringRule(minLength: 2, maxLength: 2, pattern: nil)
    public static let timeZoneRule = StringRule(minLength: 0, maxLength: 64, pattern: nil)
    public var displayName: String?
    public var language: String?
    public var region: String?
    public var timeZone: String?

    public init(displayName: String? = nil, language: String? = nil, region: String? = nil, timeZone: String? = nil) {
        self.displayName = displayName
        self.language = language
        self.region = region
        self.timeZone = timeZone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName
        case language
        case region
        case timeZone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(region, forKey: .region)
        try container.encodeIfPresent(timeZone, forKey: .timeZone)
    }
}

