//
// UpdateWatchlistItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateWatchlistItem: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case watchlist = "WATCHLIST"
        case watching = "WATCHING"
        case completed = "COMPLETED"
        case onHold = "ON_HOLD"
        case dropped = "DROPPED"
    }
    public static let ratingRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: false, maximum: 10.0, exclusiveMaximum: false, multipleOf: nil)
    public var notes: String?
    public var rating: Double?
    public var status: Status?

    public init(notes: String? = nil, rating: Double? = nil, status: Status? = nil) {
        self.notes = notes
        self.rating = rating
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notes
        case rating
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

