//
// UpdateSeriesNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateSeriesNotification: Sendable, Codable, Hashable {

    public var newEpisodes: Bool

    public init(newEpisodes: Bool) {
        self.newEpisodes = newEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newEpisodes, forKey: .newEpisodes)
    }
}

