//
// UpNextResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpNextResponse: Sendable, Codable, Hashable {

    public var airedEpisodes: Int
    public var lastWatchedAt: Date?
    public var nextEpisodeCode: String
    public var nextEpisodeId: Int64
    public var nextEpisodeName: String?
    public var nextEpisodeStillUrl: String?
    public var posterUrl: String?
    public var primaryTitle: String
    public var titleId: Int64
    public var watchedEpisodes: Int

    public init(airedEpisodes: Int, lastWatchedAt: Date? = nil, nextEpisodeCode: String, nextEpisodeId: Int64, nextEpisodeName: String? = nil, nextEpisodeStillUrl: String? = nil, posterUrl: String? = nil, primaryTitle: String, titleId: Int64, watchedEpisodes: Int) {
        self.airedEpisodes = airedEpisodes
        self.lastWatchedAt = lastWatchedAt
        self.nextEpisodeCode = nextEpisodeCode
        self.nextEpisodeId = nextEpisodeId
        self.nextEpisodeName = nextEpisodeName
        self.nextEpisodeStillUrl = nextEpisodeStillUrl
        self.posterUrl = posterUrl
        self.primaryTitle = primaryTitle
        self.titleId = titleId
        self.watchedEpisodes = watchedEpisodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case airedEpisodes
        case lastWatchedAt
        case nextEpisodeCode
        case nextEpisodeId
        case nextEpisodeName
        case nextEpisodeStillUrl
        case posterUrl
        case primaryTitle
        case titleId
        case watchedEpisodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(airedEpisodes, forKey: .airedEpisodes)
        try container.encodeIfPresent(lastWatchedAt, forKey: .lastWatchedAt)
        try container.encode(nextEpisodeCode, forKey: .nextEpisodeCode)
        try container.encode(nextEpisodeId, forKey: .nextEpisodeId)
        try container.encodeIfPresent(nextEpisodeName, forKey: .nextEpisodeName)
        try container.encodeIfPresent(nextEpisodeStillUrl, forKey: .nextEpisodeStillUrl)
        try container.encodeIfPresent(posterUrl, forKey: .posterUrl)
        try container.encode(primaryTitle, forKey: .primaryTitle)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(watchedEpisodes, forKey: .watchedEpisodes)
    }
}

