//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserResponse: Sendable, Codable, Hashable {

    public var displayName: String
    public var email: String
    public var id: Int64
    public var language: String
    public var region: String
    public var timeZone: String

    public init(displayName: String, email: String, id: Int64, language: String, region: String, timeZone: String) {
        self.displayName = displayName
        self.email = email
        self.id = id
        self.language = language
        self.region = region
        self.timeZone = timeZone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName
        case email
        case id
        case language
        case region
        case timeZone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(email, forKey: .email)
        try container.encode(id, forKey: .id)
        try container.encode(language, forKey: .language)
        try container.encode(region, forKey: .region)
        try container.encode(timeZone, forKey: .timeZone)
    }
}


extension UserResponse: Identifiable {}
