//
// WatchStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchStats: Sendable, Codable, Hashable {

    public var byGenre: [Bucket]
    public var byMonth: [MonthBucket]
    public var byService: [Bucket]
    public var byStatus: [String: Int64]
    public var currentStreakDays: Int
    public var distinctTitles: Int64
    public var firstWatchedAt: Date?
    public var lastWatchedAt: Date?
    public var longestStreakDays: Int
    public var minutesLast30Days: Int64
    public var minutesLast365Days: Int64
    public var topTitles: [Bucket]
    public var totalEpisodeViewings: Int64
    public var totalMinutes: Int64
    public var totalMovieViewings: Int64

    public init(byGenre: [Bucket], byMonth: [MonthBucket], byService: [Bucket], byStatus: [String: Int64], currentStreakDays: Int, distinctTitles: Int64, firstWatchedAt: Date? = nil, lastWatchedAt: Date? = nil, longestStreakDays: Int, minutesLast30Days: Int64, minutesLast365Days: Int64, topTitles: [Bucket], totalEpisodeViewings: Int64, totalMinutes: Int64, totalMovieViewings: Int64) {
        self.byGenre = byGenre
        self.byMonth = byMonth
        self.byService = byService
        self.byStatus = byStatus
        self.currentStreakDays = currentStreakDays
        self.distinctTitles = distinctTitles
        self.firstWatchedAt = firstWatchedAt
        self.lastWatchedAt = lastWatchedAt
        self.longestStreakDays = longestStreakDays
        self.minutesLast30Days = minutesLast30Days
        self.minutesLast365Days = minutesLast365Days
        self.topTitles = topTitles
        self.totalEpisodeViewings = totalEpisodeViewings
        self.totalMinutes = totalMinutes
        self.totalMovieViewings = totalMovieViewings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case byGenre
        case byMonth
        case byService
        case byStatus
        case currentStreakDays
        case distinctTitles
        case firstWatchedAt
        case lastWatchedAt
        case longestStreakDays
        case minutesLast30Days
        case minutesLast365Days
        case topTitles
        case totalEpisodeViewings
        case totalMinutes
        case totalMovieViewings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(byGenre, forKey: .byGenre)
        try container.encode(byMonth, forKey: .byMonth)
        try container.encode(byService, forKey: .byService)
        try container.encode(byStatus, forKey: .byStatus)
        try container.encode(currentStreakDays, forKey: .currentStreakDays)
        try container.encode(distinctTitles, forKey: .distinctTitles)
        try container.encodeIfPresent(firstWatchedAt, forKey: .firstWatchedAt)
        try container.encodeIfPresent(lastWatchedAt, forKey: .lastWatchedAt)
        try container.encode(longestStreakDays, forKey: .longestStreakDays)
        try container.encode(minutesLast30Days, forKey: .minutesLast30Days)
        try container.encode(minutesLast365Days, forKey: .minutesLast365Days)
        try container.encode(topTitles, forKey: .topTitles)
        try container.encode(totalEpisodeViewings, forKey: .totalEpisodeViewings)
        try container.encode(totalMinutes, forKey: .totalMinutes)
        try container.encode(totalMovieViewings, forKey: .totalMovieViewings)
    }
}

