//
// WatchlistItemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchlistItemResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case watchlist = "WATCHLIST"
        case watching = "WATCHING"
        case completed = "COMPLETED"
        case onHold = "ON_HOLD"
        case dropped = "DROPPED"
    }
    public var addedAt: Date
    public var completedAt: Date?
    public var favorite: Bool
    public var id: Int64
    public var notes: String?
    public var priority: Int
    public var startedAt: Date?
    public var status: Status
    public var title: TitleResponse
    public var userRating: Double?

    public init(addedAt: Date, completedAt: Date? = nil, favorite: Bool, id: Int64, notes: String? = nil, priority: Int, startedAt: Date? = nil, status: Status, title: TitleResponse, userRating: Double? = nil) {
        self.addedAt = addedAt
        self.completedAt = completedAt
        self.favorite = favorite
        self.id = id
        self.notes = notes
        self.priority = priority
        self.startedAt = startedAt
        self.status = status
        self.title = title
        self.userRating = userRating
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addedAt
        case completedAt
        case favorite
        case id
        case notes
        case priority
        case startedAt
        case status
        case title
        case userRating
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addedAt, forKey: .addedAt)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(favorite, forKey: .favorite)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(priority, forKey: .priority)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(userRating, forKey: .userRating)
    }
}


extension WatchlistItemResponse: Identifiable {}
