//
// WatchEventResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WatchEventResponse: Sendable, Codable, Hashable {

    public var episodeCode: String?
    public var episodeId: Int64?
    public var episodeName: String?
    public var id: Int64
    public var minutesWatched: Int?
    public var primaryTitle: String
    public var rewatch: Bool
    public var streamingServiceName: String?
    public var titleId: Int64
    public var watchedAt: Date

    public init(episodeCode: String? = nil, episodeId: Int64? = nil, episodeName: String? = nil, id: Int64, minutesWatched: Int? = nil, primaryTitle: String, rewatch: Bool, streamingServiceName: String? = nil, titleId: Int64, watchedAt: Date) {
        self.episodeCode = episodeCode
        self.episodeId = episodeId
        self.episodeName = episodeName
        self.id = id
        self.minutesWatched = minutesWatched
        self.primaryTitle = primaryTitle
        self.rewatch = rewatch
        self.streamingServiceName = streamingServiceName
        self.titleId = titleId
        self.watchedAt = watchedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episodeCode
        case episodeId
        case episodeName
        case id
        case minutesWatched
        case primaryTitle
        case rewatch
        case streamingServiceName
        case titleId
        case watchedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(episodeCode, forKey: .episodeCode)
        try container.encodeIfPresent(episodeId, forKey: .episodeId)
        try container.encodeIfPresent(episodeName, forKey: .episodeName)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(minutesWatched, forKey: .minutesWatched)
        try container.encode(primaryTitle, forKey: .primaryTitle)
        try container.encode(rewatch, forKey: .rewatch)
        try container.encodeIfPresent(streamingServiceName, forKey: .streamingServiceName)
        try container.encode(titleId, forKey: .titleId)
        try container.encode(watchedAt, forKey: .watchedAt)
    }
}


extension WatchEventResponse: Identifiable {}
