-- ---------------------------------------------------------------------------
-- Bookkeeping for the IMDb ratings enrichment job.
--
-- title.imdb_rating and title.imdb_vote_count have existed since V1 and were
-- never populated. They are filled from IMDb's published bulk datasets, which
-- are refreshed daily.
--
-- This table exists so a silently failing nightly job is visible. A job that
-- stops working and says nothing is indistinguishable from one that has
-- nothing to do.
-- ---------------------------------------------------------------------------

CREATE TABLE imdb_import_run
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    started_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    finished_at          TIMESTAMP(6) WITH TIME ZONE,
    status               VARCHAR(16) NOT NULL DEFAULT 'RUNNING',

    -- Last-Modified reported by the dataset host on the run that produced this
    -- row. The next run sends it as If-Modified-Since: IMDb republishes daily,
    -- so re-downloading an unchanged file is pure waste.
    source_last_modified VARCHAR(64),

    -- rows_read counts lines seen, rows_parsed those that survived parsing,
    -- rows_updated those that actually matched a title we hold and changed it.
    -- The gap between the last two is expected and large: IMDb publishes
    -- ratings for millions of titles this catalog has never heard of.
    rows_read            BIGINT      NOT NULL DEFAULT 0,
    rows_parsed          BIGINT      NOT NULL DEFAULT 0,
    rows_updated         BIGINT      NOT NULL DEFAULT 0,
    error_message        TEXT,

    CONSTRAINT ck_imdb_import_status CHECK (status IN
        ('RUNNING', 'SUCCESS', 'SKIPPED_NOT_MODIFIED', 'FAILED'))
);

CREATE INDEX idx_imdb_import_run_started_at ON imdb_import_run (started_at DESC);
