-- ---------------------------------------------------------------------------
-- V9: connecting Trakt (#39).
--
-- Trakt is the opposite shape to Plex. There, the user's server calls us and
-- we hold no credential of theirs; here we hold an OAuth access and refresh
-- token and call Trakt on their behalf, which is the first time this service
-- holds a credential belonging to somebody else's account.
--
-- So the token never sits in a column. It is encrypted with AES-GCM under a
-- key that lives in the deployment's configuration rather than in the
-- database, and only the ciphertext is stored here -- which is what
-- linked_streaming_account.credential_ref has always promised by pointing at
-- "an entry in a secret manager" rather than holding the secret itself. A
-- dump of this database, without the key, yields nothing usable.
-- ---------------------------------------------------------------------------

CREATE TABLE streaming_credential
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What linked_streaming_account.credential_ref points at.
    credential_ref VARCHAR(64)  NOT NULL,

    -- AES-GCM: the ciphertext, the nonce it was sealed with, and which key
    -- did it. key_id is what makes a key rotation legible rather than a guess:
    -- a row sealed under a retired key can be told apart from a corrupt one.
    ciphertext     TEXT         NOT NULL,
    nonce          VARCHAR(64)  NOT NULL,
    key_id         VARCHAR(64)  NOT NULL,

    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT uq_streaming_credential_ref UNIQUE (credential_ref)
);

-- One authorisation in progress.
--
-- The state parameter is what ties the browser that comes back from Trakt to
-- the user who started the flow; without it, anybody who can reach the
-- callback could attach their own Trakt account to somebody else's library.
-- Stored as a hash and deleted on use, because it travels through a browser
-- and through Trakt's redirect: it is a bearer value like any other.
CREATE TABLE oauth_state
(
    state_hash VARCHAR(64)  NOT NULL PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    provider   VARCHAR(32)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_oauth_state_expires ON oauth_state (expires_at);

-- Trakt earns supports_sync for the reason the other rows do not: it has a
-- documented API for a user's own viewing history, and the user authorises it
-- themselves rather than handing over a password.
INSERT INTO streaming_service (slug, name, supports_sync)
VALUES ('trakt', 'Trakt', TRUE)
ON CONFLICT (slug) DO UPDATE SET supports_sync = TRUE;
