-- ---------------------------------------------------------------------------
-- Watch Guru initial schema.
--
-- Layout follows three concerns that evolve at different rates:
--   1. catalog  - metadata mirrored from TMDB, keyed by imdb_id where known
--   2. tracking - what a user has watched, at title and episode granularity
--   3. sync     - streaming services, availability, and linked accounts
-- ---------------------------------------------------------------------------


-- === 1. catalog ============================================================

CREATE TABLE title
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- TMDB ids are only unique within a media type, so the natural key is the
    -- pair. imdb_id is the cross-source identifier and stays nullable because
    -- TMDB does not have one for every title.
    tmdb_id                BIGINT       NOT NULL,
    title_type             VARCHAR(16)  NOT NULL,
    imdb_id                VARCHAR(16),

    primary_title          VARCHAR(512) NOT NULL,
    original_title         VARCHAR(512),
    tagline                VARCHAR(512),
    overview               TEXT,
    original_language      VARCHAR(16),
    homepage               VARCHAR(1024),
    poster_path            VARCHAR(255),
    backdrop_path          VARCHAR(255),

    -- Movies use release_date; series use first/last air date.
    release_date           DATE,
    first_air_date         DATE,
    last_air_date          DATE,
    production_status      VARCHAR(64),
    adult                  BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Movie runtime, or the typical episode runtime for a series.
    runtime_minutes        INTEGER,
    number_of_seasons      INTEGER,
    number_of_episodes     INTEGER,

    tmdb_vote_average      NUMERIC(4, 2),
    tmdb_vote_count        INTEGER,
    tmdb_popularity        NUMERIC(10, 3),

    -- Populated from the IMDb ratings dataset if that import is added later.
    imdb_rating            NUMERIC(3, 1),
    imdb_vote_count        INTEGER,

    -- Cache bookkeeping: summary rows arrive from search results, detail rows
    -- from a full fetch. A null detail_fetched_at means "search stub only".
    summary_fetched_at     TIMESTAMP(6) WITH TIME ZONE,
    detail_fetched_at      TIMESTAMP(6) WITH TIME ZONE,
    availability_fetched_at TIMESTAMP(6) WITH TIME ZONE,

    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version                BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_title_tmdb UNIQUE (tmdb_id, title_type),
    CONSTRAINT uq_title_imdb UNIQUE (imdb_id),
    CONSTRAINT ck_title_type CHECK (title_type IN ('MOVIE', 'TV_SERIES'))
);

CREATE INDEX idx_title_primary_title ON title (lower(primary_title));
CREATE INDEX idx_title_detail_fetched_at ON title (detail_fetched_at);

CREATE TABLE genre
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id BIGINT       NOT NULL,
    name    VARCHAR(128) NOT NULL,
    CONSTRAINT uq_genre_tmdb UNIQUE (tmdb_id)
);

CREATE TABLE title_genre
(
    title_id BIGINT NOT NULL REFERENCES title (id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genre (id) ON DELETE CASCADE,
    PRIMARY KEY (title_id, genre_id)
);

CREATE INDEX idx_title_genre_genre ON title_genre (genre_id);

CREATE TABLE season
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id      BIGINT       NOT NULL REFERENCES title (id) ON DELETE CASCADE,
    tmdb_id       BIGINT,
    season_number INTEGER      NOT NULL,
    name          VARCHAR(512),
    overview      TEXT,
    air_date      DATE,
    episode_count INTEGER,
    poster_path   VARCHAR(255),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_season_number UNIQUE (title_id, season_number)
);

CREATE TABLE episode
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id         BIGINT       NOT NULL REFERENCES season (id) ON DELETE CASCADE,

    -- Denormalised so title-wide episode queries avoid a join through season.
    title_id          BIGINT       NOT NULL REFERENCES title (id) ON DELETE CASCADE,

    tmdb_id           BIGINT,
    season_number     INTEGER      NOT NULL,
    episode_number    INTEGER      NOT NULL,
    name              VARCHAR(512),
    overview          TEXT,
    air_date          DATE,
    runtime_minutes   INTEGER,
    still_path        VARCHAR(255),
    tmdb_vote_average NUMERIC(4, 2),
    created_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_episode_number UNIQUE (season_id, episode_number)
);

CREATE INDEX idx_episode_title ON episode (title_id);


-- === 2. users and tracking =================================================

CREATE TABLE app_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Reserved for an OIDC subject once real authentication is wired up.
    auth_subject VARCHAR(255),
    email        VARCHAR(320) NOT NULL,
    display_name VARCHAR(128) NOT NULL,

    -- Region drives which streaming offers are relevant to this user.
    region       VARCHAR(2)   NOT NULL DEFAULT 'US',
    language     VARCHAR(16)  NOT NULL DEFAULT 'en-US',
    time_zone    VARCHAR(64)  NOT NULL DEFAULT 'UTC',

    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT uq_app_user_auth_subject UNIQUE (auth_subject)
);

CREATE TABLE watchlist_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    title_id      BIGINT      NOT NULL REFERENCES title (id) ON DELETE CASCADE,

    status        VARCHAR(16) NOT NULL,
    priority      INTEGER     NOT NULL DEFAULT 0,
    favorite      BOOLEAN     NOT NULL DEFAULT FALSE,
    user_rating   NUMERIC(4, 2),
    notes         TEXT,

    added_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    started_at    TIMESTAMP(6) WITH TIME ZONE,
    completed_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version       BIGINT      NOT NULL DEFAULT 0,

    -- Provenance: how the item got here, and its id in the source system.
    -- Lets a Netflix/Disney+ import be re-run idempotently and lets the user
    -- see which entries they added by hand.
    origin        VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    origin_ref    VARCHAR(255),

    CONSTRAINT uq_watchlist_user_title UNIQUE (user_id, title_id),
    CONSTRAINT ck_watchlist_status CHECK (status IN
        ('WATCHLIST', 'WATCHING', 'COMPLETED', 'ON_HOLD', 'DROPPED')),
    CONSTRAINT ck_watchlist_rating CHECK (user_rating IS NULL OR (user_rating >= 0 AND user_rating <= 10))
);

CREATE INDEX idx_watchlist_user_status ON watchlist_item (user_id, status);
CREATE INDEX idx_watchlist_title ON watchlist_item (title_id);

-- Current per-episode progress. One row per user/episode; rewatches bump
-- watch_count rather than inserting duplicates.
CREATE TABLE episode_watch
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT  NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    episode_id    BIGINT  NOT NULL REFERENCES episode (id) ON DELETE CASCADE,
    title_id      BIGINT  NOT NULL REFERENCES title (id) ON DELETE CASCADE,

    watched_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    watch_count   INTEGER NOT NULL DEFAULT 1,
    user_rating   NUMERIC(4, 2),
    version       BIGINT  NOT NULL DEFAULT 0,

    CONSTRAINT uq_episode_watch UNIQUE (user_id, episode_id),
    CONSTRAINT ck_episode_watch_count CHECK (watch_count > 0)
);

CREATE INDEX idx_episode_watch_user_title ON episode_watch (user_id, title_id);

-- Append-only viewing history. This is the table that answers "how much have
-- I watched", "when", "on which service" and "was it a rewatch"; the tables
-- above only hold current state.
CREATE TABLE watch_event
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    title_id             BIGINT      NOT NULL REFERENCES title (id) ON DELETE CASCADE,

    -- Null for a movie; set for a series episode.
    episode_id           BIGINT REFERENCES episode (id) ON DELETE CASCADE,

    watched_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    minutes_watched      INTEGER,
    completed            BOOLEAN     NOT NULL DEFAULT TRUE,
    rewatch              BOOLEAN     NOT NULL DEFAULT FALSE,

    streaming_service_id BIGINT,
    origin               VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    origin_ref           VARCHAR(255),
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT ck_watch_event_minutes CHECK (minutes_watched IS NULL OR minutes_watched >= 0)
);

CREATE INDEX idx_watch_event_user_watched_at ON watch_event (user_id, watched_at DESC);
CREATE INDEX idx_watch_event_user_title ON watch_event (user_id, title_id);
CREATE INDEX idx_watch_event_episode ON watch_event (episode_id);

-- Guards against importing the same external record twice.
CREATE UNIQUE INDEX uq_watch_event_origin
    ON watch_event (user_id, origin, origin_ref)
    WHERE origin_ref IS NOT NULL;


-- === 3. streaming services, availability, sync =============================

CREATE TABLE streaming_service
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(64)  NOT NULL,
    name             VARCHAR(128) NOT NULL,

    -- TMDB watch-provider id, used to map availability responses onto rows here.
    tmdb_provider_id BIGINT,
    logo_path        VARCHAR(255),

    -- Whether a direct account integration exists yet. Availability data works
    -- for every service; only these can sync a user's own list.
    supports_sync    BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_streaming_service_slug UNIQUE (slug),
    CONSTRAINT uq_streaming_service_tmdb UNIQUE (tmdb_provider_id)
);

ALTER TABLE watch_event
    ADD CONSTRAINT fk_watch_event_service
        FOREIGN KEY (streaming_service_id) REFERENCES streaming_service (id) ON DELETE SET NULL;

-- Where a title can be streamed, per region and offer type, from TMDB.
CREATE TABLE title_availability
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id             BIGINT      NOT NULL REFERENCES title (id) ON DELETE CASCADE,
    streaming_service_id BIGINT      NOT NULL REFERENCES streaming_service (id) ON DELETE CASCADE,
    region               VARCHAR(2)  NOT NULL,
    offer_type           VARCHAR(16) NOT NULL,
    link                 VARCHAR(1024),
    fetched_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT uq_title_availability UNIQUE (title_id, streaming_service_id, region, offer_type),
    CONSTRAINT ck_availability_offer_type CHECK (offer_type IN
        ('FLATRATE', 'RENT', 'BUY', 'ADS', 'FREE'))
);

CREATE INDEX idx_title_availability_region ON title_availability (region, streaming_service_id);

-- A user's connection to a streaming account. Credentials are deliberately
-- NOT stored here: credential_ref points at an entry in a secret manager so
-- tokens never land in the application database or its backups.
CREATE TABLE linked_streaming_account
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    streaming_service_id BIGINT      NOT NULL REFERENCES streaming_service (id) ON DELETE CASCADE,

    account_label        VARCHAR(128),
    status               VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    credential_ref       VARCHAR(255),
    sync_enabled         BOOLEAN     NOT NULL DEFAULT TRUE,

    last_sync_at         TIMESTAMP(6) WITH TIME ZONE,
    last_sync_cursor     VARCHAR(255),
    last_sync_error      TEXT,

    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    version              BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_linked_account UNIQUE (user_id, streaming_service_id),
    CONSTRAINT ck_linked_account_status CHECK (status IN
        ('PENDING', 'CONNECTED', 'ERROR', 'REVOKED', 'DISCONNECTED'))
);

CREATE TABLE sync_run
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    linked_account_id BIGINT      NOT NULL REFERENCES linked_streaming_account (id) ON DELETE CASCADE,

    started_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT now(),
    finished_at       TIMESTAMP(6) WITH TIME ZONE,
    status            VARCHAR(16) NOT NULL DEFAULT 'RUNNING',
    items_imported    INTEGER     NOT NULL DEFAULT 0,
    items_skipped     INTEGER     NOT NULL DEFAULT 0,
    items_failed      INTEGER     NOT NULL DEFAULT 0,
    error_message     TEXT,

    CONSTRAINT ck_sync_run_status CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED'))
);

CREATE INDEX idx_sync_run_account ON sync_run (linked_account_id, started_at DESC);
