//
// AuthenticationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AuthenticationAPI {

    /**
     Exchange a provider ID token for a session
     
     - parameter exchangeToken: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SessionResponse
     */
    open class func createSession(exchangeToken: ExchangeToken, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> SessionResponse {
        return try await createSessionWithRequestBuilder(exchangeToken: exchangeToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Exchange a provider ID token for a session
     - POST /api/v1/auth/session
     - Verifies the provider's ID token and returns an access token and a refresh token issued by this service. Provisions the account on first use.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter exchangeToken: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SessionResponse> 
     */
    open class func createSessionWithRequestBuilder(exchangeToken: ExchangeToken, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<SessionResponse> {
        let localVariablePath = "/api/v1/auth/session"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: exchangeToken, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SessionResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Revoke a session
     
     - parameter refreshSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func endSession(refreshSession: RefreshSession, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await endSessionWithRequestBuilder(refreshSession: refreshSession, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Revoke a session
     - POST /api/v1/auth/logout
     - Revokes the refresh token and every token descended from the same sign-in. Succeeds even if the token was already invalid.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter refreshSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func endSessionWithRequestBuilder(refreshSession: RefreshSession, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/auth/logout"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshSession, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Exchange a refresh token for a new session
     
     - parameter refreshSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SessionResponse
     */
    open class func refreshSession(refreshSession: RefreshSession, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> SessionResponse {
        return try await refreshSessionWithRequestBuilder(refreshSession: refreshSession, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Exchange a refresh token for a new session
     - POST /api/v1/auth/refresh
     - Rotates the refresh token. The presented token is invalidated, and presenting it a second time revokes the entire session.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter refreshSession: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SessionResponse> 
     */
    open class func refreshSessionWithRequestBuilder(refreshSession: RefreshSession, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<SessionResponse> {
        let localVariablePath = "/api/v1/auth/refresh"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshSession, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SessionResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
