//
// ImportControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ImportControllerAPI {

    /**

     - parameter commitImport: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ImportResultResponse
     */
    open class func commitImport(commitImport: CommitImport, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> ImportResultResponse {
        return try await commitImportWithRequestBuilder(commitImport: commitImport, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/imports
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter commitImport: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImportResultResponse> 
     */
    open class func commitImportWithRequestBuilder(commitImport: CommitImport, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<ImportResultResponse> {
        let localVariablePath = "/api/v1/me/imports"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: commitImport, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImportResultResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter previewImport: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ImportPreviewResponse
     */
    open class func previewImport(previewImport: PreviewImport, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> ImportPreviewResponse {
        return try await previewImportWithRequestBuilder(previewImport: previewImport, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/imports/preview
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter previewImport: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ImportPreviewResponse> 
     */
    open class func previewImportWithRequestBuilder(previewImport: PreviewImport, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<ImportPreviewResponse> {
        let localVariablePath = "/api/v1/me/imports/preview"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: previewImport, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImportPreviewResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
