//
// MediaServerControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MediaServerControllerAPI {

    /**

     - parameter service: (path)  
     - parameter connectMediaServer: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MediaServerConnectionResponse
     */
    open class func connectMediaServer(service: String, connectMediaServer: ConnectMediaServer? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> MediaServerConnectionResponse {
        return try await connectMediaServerWithRequestBuilder(service: service, connectMediaServer: connectMediaServer, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/streaming-accounts/servers/{service}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter service: (path)  
     - parameter connectMediaServer: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MediaServerConnectionResponse> 
     */
    open class func connectMediaServerWithRequestBuilder(service: String, connectMediaServer: ConnectMediaServer? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<MediaServerConnectionResponse> {
        var localVariablePath = "/api/v1/me/streaming-accounts/servers/{service}"
        let servicePreEscape = "\(APIHelper.mapValueToPathItem(service))"
        let servicePostEscape = servicePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{service}", with: servicePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: connectMediaServer, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MediaServerConnectionResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter service: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func disconnectMediaServer(service: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await disconnectMediaServerWithRequestBuilder(service: service, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v1/me/streaming-accounts/servers/{service}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter service: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func disconnectMediaServerWithRequestBuilder(service: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/streaming-accounts/servers/{service}"
        let servicePreEscape = "\(APIHelper.mapValueToPathItem(service))"
        let servicePostEscape = servicePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{service}", with: servicePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter service: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MediaServerStatusResponse
     */
    open class func getMediaServerStatus(service: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> MediaServerStatusResponse {
        return try await getMediaServerStatusWithRequestBuilder(service: service, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/streaming-accounts/servers/{service}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter service: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MediaServerStatusResponse> 
     */
    open class func getMediaServerStatusWithRequestBuilder(service: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<MediaServerStatusResponse> {
        var localVariablePath = "/api/v1/me/streaming-accounts/servers/{service}"
        let servicePreEscape = "\(APIHelper.mapValueToPathItem(service))"
        let servicePostEscape = servicePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{service}", with: servicePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MediaServerStatusResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
