//
// NotificationControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class NotificationControllerAPI {

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: NotificationSettingsResponse
     */
    open class func getNotificationSettings(apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> NotificationSettingsResponse {
        return try await getNotificationSettingsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/notifications
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<NotificationSettingsResponse> 
     */
    open class func getNotificationSettingsWithRequestBuilder(apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<NotificationSettingsResponse> {
        let localVariablePath = "/api/v1/me/notifications"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NotificationSettingsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter registerDevice: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func registerDevice(registerDevice: RegisterDevice, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await registerDeviceWithRequestBuilder(registerDevice: registerDevice, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/devices
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter registerDevice: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func registerDeviceWithRequestBuilder(registerDevice: RegisterDevice, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/me/devices"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerDevice, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter token: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func unregisterDevice(token: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await unregisterDeviceWithRequestBuilder(token: token, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v1/me/devices/{token}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter token: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func unregisterDeviceWithRequestBuilder(token: String, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/devices/{token}"
        let tokenPreEscape = "\(APIHelper.mapValueToPathItem(token))"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter updateNotificationSettings: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: NotificationSettingsResponse
     */
    open class func updateNotificationSettings(updateNotificationSettings: UpdateNotificationSettings, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> NotificationSettingsResponse {
        return try await updateNotificationSettingsWithRequestBuilder(updateNotificationSettings: updateNotificationSettings, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PATCH /api/v1/me/notifications
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter updateNotificationSettings: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<NotificationSettingsResponse> 
     */
    open class func updateNotificationSettingsWithRequestBuilder(updateNotificationSettings: UpdateNotificationSettings, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<NotificationSettingsResponse> {
        let localVariablePath = "/api/v1/me/notifications"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateNotificationSettings, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NotificationSettingsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter titleId: (path)  
     - parameter updateSeriesNotification: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: NotificationSettingsResponse
     */
    open class func updateSeriesNotification(titleId: Int64, updateSeriesNotification: UpdateSeriesNotification, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> NotificationSettingsResponse {
        return try await updateSeriesNotificationWithRequestBuilder(titleId: titleId, updateSeriesNotification: updateSeriesNotification, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PUT /api/v1/me/notifications/titles/{titleId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter titleId: (path)  
     - parameter updateSeriesNotification: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<NotificationSettingsResponse> 
     */
    open class func updateSeriesNotificationWithRequestBuilder(titleId: Int64, updateSeriesNotification: UpdateSeriesNotification, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<NotificationSettingsResponse> {
        var localVariablePath = "/api/v1/me/notifications/titles/{titleId}"
        let titleIdPreEscape = "\(APIHelper.mapValueToPathItem(titleId))"
        let titleIdPostEscape = titleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{titleId}", with: titleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateSeriesNotification, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NotificationSettingsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
