//
// TitleControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TitleControllerAPI {

    /**

     - parameter titleId: (path)  
     - parameter region: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TitleResponse
     */
    open class func getTitle(titleId: Int64, region: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> TitleResponse {
        return try await getTitleWithRequestBuilder(titleId: titleId, region: region, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/titles/{titleId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter titleId: (path)  
     - parameter region: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TitleResponse> 
     */
    open class func getTitleWithRequestBuilder(titleId: Int64, region: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<TitleResponse> {
        var localVariablePath = "/api/v1/titles/{titleId}"
        let titleIdPreEscape = "\(APIHelper.mapValueToPathItem(titleId))"
        let titleIdPostEscape = titleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{titleId}", with: titleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "region": (wrappedValue: region?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TitleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter titleType
     */
    public enum TitleType_importTitle: String, Sendable, CaseIterable {
        case movie = "MOVIE"
        case tvSeries = "TV_SERIES"
    }

    /**

     - parameter titleType: (query)  
     - parameter providerId: (query)  
     - parameter language: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TitleResponse
     */
    open class func importTitle(titleType: TitleType_importTitle, providerId: Int64, language: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> TitleResponse {
        return try await importTitleWithRequestBuilder(titleType: titleType, providerId: providerId, language: language, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/titles/import
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter titleType: (query)  
     - parameter providerId: (query)  
     - parameter language: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TitleResponse> 
     */
    open class func importTitleWithRequestBuilder(titleType: TitleType_importTitle, providerId: Int64, language: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<TitleResponse> {
        let localVariablePath = "/api/v1/titles/import"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "titleType": (wrappedValue: titleType.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "providerId": (wrappedValue: providerId.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language": (wrappedValue: language?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TitleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter query: (query)  
     - parameter page: (query)  (optional, default to 1)
     - parameter language: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SearchResponse
     */
    open class func searchTitles(query: String, page: Int? = nil, language: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> SearchResponse {
        return try await searchTitlesWithRequestBuilder(query: query, page: page, language: language, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/titles/search
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter query: (query)  
     - parameter page: (query)  (optional, default to 1)
     - parameter language: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SearchResponse> 
     */
    open class func searchTitlesWithRequestBuilder(query: String, page: Int? = nil, language: String? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<SearchResponse> {
        let localVariablePath = "/api/v1/titles/search"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "language": (wrappedValue: language?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SearchResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
