//
// WatchlistControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WatchlistControllerAPI {

    /**

     - parameter addToWatchlist: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WatchlistItemResponse
     */
    open class func addToWatchlist(addToWatchlist: AddToWatchlist, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> WatchlistItemResponse {
        return try await addToWatchlistWithRequestBuilder(addToWatchlist: addToWatchlist, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/watchlist
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter addToWatchlist: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WatchlistItemResponse> 
     */
    open class func addToWatchlistWithRequestBuilder(addToWatchlist: AddToWatchlist, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<WatchlistItemResponse> {
        let localVariablePath = "/api/v1/me/watchlist"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addToWatchlist, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchlistItemResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter titleId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TitleProgress
     */
    open class func getTitleProgress(titleId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> TitleProgress {
        return try await getTitleProgressWithRequestBuilder(titleId: titleId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/watchlist/titles/{titleId}/progress
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter titleId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TitleProgress> 
     */
    open class func getTitleProgressWithRequestBuilder(titleId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<TitleProgress> {
        var localVariablePath = "/api/v1/me/watchlist/titles/{titleId}/progress"
        let titleIdPreEscape = "\(APIHelper.mapValueToPathItem(titleId))"
        let titleIdPostEscape = titleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{titleId}", with: titleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TitleProgress>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter status
     */
    public enum Status_listWatchlist: String, Sendable, CaseIterable {
        case watchlist = "WATCHLIST"
        case watching = "WATCHING"
        case completed = "COMPLETED"
        case onHold = "ON_HOLD"
        case dropped = "DROPPED"
    }

    /**

     - parameter status: (query)  (optional)
     - parameter page: (query)  (optional, default to 0)
     - parameter size: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [WatchlistItemResponse]
     */
    open class func listWatchlist(status: Status_listWatchlist? = nil, page: Int? = nil, size: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> [WatchlistItemResponse] {
        return try await listWatchlistWithRequestBuilder(status: status, page: page, size: size, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/watchlist
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter status: (query)  (optional)
     - parameter page: (query)  (optional, default to 0)
     - parameter size: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[WatchlistItemResponse]> 
     */
    open class func listWatchlistWithRequestBuilder(status: Status_listWatchlist? = nil, page: Int? = nil, size: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<[WatchlistItemResponse]> {
        let localVariablePath = "/api/v1/me/watchlist"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": (wrappedValue: status?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[WatchlistItemResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter itemId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func removeFromWatchlist(itemId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await removeFromWatchlistWithRequestBuilder(itemId: itemId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v1/me/watchlist/{itemId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter itemId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func removeFromWatchlistWithRequestBuilder(itemId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/watchlist/{itemId}"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{itemId}", with: itemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter itemId: (path)  
     - parameter updateWatchlistItem: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WatchlistItemResponse
     */
    open class func updateWatchlistItem(itemId: Int64, updateWatchlistItem: UpdateWatchlistItem, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> WatchlistItemResponse {
        return try await updateWatchlistItemWithRequestBuilder(itemId: itemId, updateWatchlistItem: updateWatchlistItem, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PATCH /api/v1/me/watchlist/{itemId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter itemId: (path)  
     - parameter updateWatchlistItem: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WatchlistItemResponse> 
     */
    open class func updateWatchlistItemWithRequestBuilder(itemId: Int64, updateWatchlistItem: UpdateWatchlistItem, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<WatchlistItemResponse> {
        var localVariablePath = "/api/v1/me/watchlist/{itemId}"
        let itemIdPreEscape = "\(APIHelper.mapValueToPathItem(itemId))"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{itemId}", with: itemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateWatchlistItem, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchlistItemResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
