//
// WatchHistoryControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WatchHistoryControllerAPI {

    /**

     - parameter eventId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteWatchEvent(eventId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteWatchEventWithRequestBuilder(eventId: eventId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v1/me/watch-events/{eventId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteWatchEventWithRequestBuilder(eventId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/watch-events/{eventId}"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter page: (query)  (optional, default to 0)
     - parameter size: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [WatchEventResponse]
     */
    open class func getHistory(page: Int? = nil, size: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> [WatchEventResponse] {
        return try await getHistoryWithRequestBuilder(page: page, size: size, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/history
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter page: (query)  (optional, default to 0)
     - parameter size: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[WatchEventResponse]> 
     */
    open class func getHistoryWithRequestBuilder(page: Int? = nil, size: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<[WatchEventResponse]> {
        let localVariablePath = "/api/v1/me/history"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[WatchEventResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter months: (query)  (optional, default to 12)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WatchStats
     */
    open class func getStats(months: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> WatchStats {
        return try await getStatsWithRequestBuilder(months: months, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/stats
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter months: (query)  (optional, default to 12)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WatchStats> 
     */
    open class func getStatsWithRequestBuilder(months: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<WatchStats> {
        let localVariablePath = "/api/v1/me/stats"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "months": (wrappedValue: months?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchStats>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter limit: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [UpNextResponse]
     */
    open class func getUpNext(limit: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> [UpNextResponse] {
        return try await getUpNextWithRequestBuilder(limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v1/me/up-next
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[UpNextResponse]> 
     */
    open class func getUpNextWithRequestBuilder(limit: Int? = nil, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<[UpNextResponse]> {
        let localVariablePath = "/api/v1/me/up-next"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UpNextResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter logEpisodeWatched: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WatchEventResponse
     */
    open class func logEpisodeWatched(logEpisodeWatched: LogEpisodeWatched, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> WatchEventResponse {
        return try await logEpisodeWatchedWithRequestBuilder(logEpisodeWatched: logEpisodeWatched, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/watch-events/episode
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter logEpisodeWatched: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WatchEventResponse> 
     */
    open class func logEpisodeWatchedWithRequestBuilder(logEpisodeWatched: LogEpisodeWatched, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<WatchEventResponse> {
        let localVariablePath = "/api/v1/me/watch-events/episode"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: logEpisodeWatched, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchEventResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter logMovieWatched: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WatchEventResponse
     */
    open class func logMovieWatched(logMovieWatched: LogMovieWatched, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> WatchEventResponse {
        return try await logMovieWatchedWithRequestBuilder(logMovieWatched: logMovieWatched, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/watch-events/movie
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter logMovieWatched: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WatchEventResponse> 
     */
    open class func logMovieWatchedWithRequestBuilder(logMovieWatched: LogMovieWatched, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<WatchEventResponse> {
        let localVariablePath = "/api/v1/me/watch-events/movie"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: logMovieWatched, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WatchEventResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter markWatchedUpTo: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BulkMarkResponse
     */
    open class func markWatchedUpTo(markWatchedUpTo: MarkWatchedUpTo, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) -> BulkMarkResponse {
        return try await markWatchedUpToWithRequestBuilder(markWatchedUpTo: markWatchedUpTo, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v1/me/watch-events/episodes/up-to
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter markWatchedUpTo: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BulkMarkResponse> 
     */
    open class func markWatchedUpToWithRequestBuilder(markWatchedUpTo: MarkWatchedUpTo, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<BulkMarkResponse> {
        let localVariablePath = "/api/v1/me/watch-events/episodes/up-to"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: markWatchedUpTo, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BulkMarkResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter episodeId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func unmarkEpisode(episodeId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await unmarkEpisodeWithRequestBuilder(episodeId: episodeId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v1/me/watch-events/episodes/{episodeId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter episodeId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func unmarkEpisodeWithRequestBuilder(episodeId: Int64, apiConfiguration: WatchGuruAPIAPIConfiguration = WatchGuruAPIAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/watch-events/episodes/{episodeId}"
        let episodeIdPreEscape = "\(APIHelper.mapValueToPathItem(episodeId))"
        let episodeIdPostEscape = episodeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{episodeId}", with: episodeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
