plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "dev.dhuelin.watchguru.api"
    compileSdk = 35

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // The generated client uses java.time; desugaring keeps minSdk 26
        // honest on older runtimes.
        isCoreLibraryDesugaringEnabled = true
    }

    kotlin {
        compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }

    sourceSets["main"].kotlin.srcDir("src/main/kotlin")
}

// This module is entirely generated by tools/generate-clients.sh. Do not edit
// anything under src/ -- the next regeneration will discard it. Behaviour that
// wraps the client belongs in :app, not here.
dependencies {
    api(libs.retrofit)
    api(libs.retrofit.scalars)
    api(libs.retrofit.kotlinx.serialization)
    api(libs.okhttp)
    api(libs.okhttp.logging)
    api(libs.kotlinx.serialization.json)
    api(libs.kotlinx.coroutines)
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.3")
}
